matthiasbeyer/imag

.travis.yml
src/storage/file/id.rs
src/storage/file/mod.rs
src/storage/json/parser.rs

Add travis, Homu

---

etc/cli.yml
src/cli.rs
src/configuration.rs
src/runtime.rs
src/ui/external/editor.rs
src/ui/external/mod.rs
src/ui/mod.rs

Tracking branch for implementation to call external editor and edit file contents with it.

Ui external

---

README.md
src/cli.rs
src/configuration.rs
src/main.rs
src/module/bm/mod.rs
src/module/helpers/header/mod.rs
src/module/helpers/header/tags.rs
src/module/helpers/mod.rs
src/module/helpers/utils.rs
src/module/mod.rs
src/runtime.rs
src/storage/file/hash.rs
src/storage/file/id.rs
src/storage/file/id_type.rs
src/storage/file/mod.rs
src/storage/mod.rs
src/storage/parser.rs
src/ui/file.rs
src/util/mod.rs

Still does not produce the documentation I want, though it basically works now.

Add some documentation

---

src/module/bm/mod.rs
src/storage/mod.rs

Ensure the store always honors the cache.

Fix store cache

---

Cargo.lock
Cargo.toml
etc/cli.yml
src/main.rs
src/module/bm/mod.rs

Add subcommand to `BM` to open links via xdg.
Closes #28

Bm open xdg

---

src/module/bm/mod.rs

Add info-output to some BM commands.

Bm command output

---

src/module/bm/mod.rs
src/module/helpers/cli.rs

State before was to generate functions which can be used as filter()
arguments.
State now is that there are types which can be lined up and be executed
as filters. And/Or/Not-Filters are provided and so are helper functions
to initialize objects of these filter types.
The BM module is adapted for this.
@TheNeikos can you have a look, please?

Refactor filter building into types which can be chained up

---

Cargo.lock
Cargo.toml
etc/cli.yml
src/configuration.rs
src/main.rs
src/module/bm/mod.rs
src/module/helpers/header/tags.rs
src/module/mod.rs
src/module/notes/header.rs
src/module/notes/mod.rs
src/runtime.rs
src/storage/file/mod.rs
src/ui/external/editor.rs

Module: Notes/journal
Closes #14 
Tracking branch for the module implementation.

Add module: notes (journal)

---

src/storage/file/id.rs
src/storage/file/id_type.rs

Improve output (Implementation of the `Display` trait).

(Re)implement Display for FileID, FileHash, FileIDType

---

Cargo.lock
Cargo.toml
etc/cli.yml
src/main.rs
src/module/helpers/content.rs
src/module/helpers/mod.rs
src/module/notes/mod.rs

[Notes] list links

---

Cargo.lock
Cargo.toml
src/main.rs
src/module/bm/mod.rs
src/module/notes/mod.rs
src/ui/file.rs

Colored output

---

Cargo.lock
Cargo.toml
etc/cli.yml
src/main.rs
src/module/helpers/content.rs
src/module/notes/mod.rs
src/ui/external/mod.rs

Open notes as HTML pages in browser.
Does not work fully by now, as one note should be opened, but two are opened, one in browser, one in libreoffice.
Closes #47

Notes open

---

src/module/bm/mod.rs
src/module/notes/mod.rs

Move the 
```
let parser = ...
```
Foo in each function to a module-global parser object in the module object.

Module parser

---

Cargo.lock
Cargo.toml
src/main.rs
src/module/notes/mod.rs
src/storage/mod.rs
src/storage/yaml/mod.rs
src/storage/yaml/parser.rs

I would like to add more tests.

Add yaml header parser

---

etc/cli.yml
src/cli.rs
src/configuration.rs
src/main.rs
src/runtime.rs

Report success (as simple "Ok"/"Error" string) to the user, if the user wants that.

Report success

---

etc/cli.yml
src/module/bm/mod.rs
src/module/notes/mod.rs
src/ui/file.rs

Support for printing plain ASCII-Tables without borders and such.

Tableprinter pretty

---

Cargo.toml

Just some improvements to `Cargo.toml`

Add more metadata for project

---

Cargo.lock
Cargo.toml
src/ui/file.rs

prettytable-rs: 0.4.0 -> 0.5.1

---

doc/Makefile
doc/templates/css/table.css

CSS setup for the paper, including table CSS.

Doc html template css setup

---

doc/src/03100-lib-rt.md
doc/src/06000-modules.md

Includes definition of runtime library.

Doc define modules

---

.editorconfig

Adds a configuration file for editorconfig, which I encourage you all to use when submitting PRs to this project :smile:.

Add editorconfig configuration file

---

doc/src/02000-store.md

Related to #76.
@TheNeikos , @neithernut Would like to hear suggestions.

Define file format

---

doc/src/01000-intro.md

Introduction.
@TheNeikos could you please correct my spelling and grammar?

doc: Add introduction

---

libimagstore/src/store.rs

Add Store::new()

---

libimagstore/src/error.rs
libimagstore/src/store.rs

Remove unused imports

---

libimagstore/src/error.rs
libimagstore/src/store.rs

Implement `Store::delete()`

---

libimagutil/src/lib.rs
libimagutil/src/variants.rs

Libimagutil init

---

libimagstore/Cargo.lock
libimagstore/Cargo.toml
libimagstore/src/error.rs
libimagstore/src/lazyfile.rs
libimagstore/src/lib.rs

@matthiasbeyer, @neithernut A possible implementation of a lazy enum to have lazy loading of files.

Add file creation

---

libimagrt/src/error.rs
libimagrt/src/lib.rs
libimagrt/src/runtime.rs
libimagstore/src/error.rs
libimagstore/src/store.rs

`Store::new()` behaviour if the store does not exist yet.

Store::new(): Create path if nonexistent

---

libimagstore/src/store.rs

This PR targets a primary issue laid out in #103.

Fix Store::retrieve()

---

libimagstore/src/store.rs

Fix: seek() file back on reading it

---

libimagstore/src/store.rs

Fix: negation error

---

libimagstore/src/storeid.rs

Fixes missing documentation in @TheNeikos awesome macro.

Fix: Add missing documentation for mod module_path

---

libimagrt/src/runtime.rs

Fix: Use env(HOME) instead of "~"

---

libimagstore/src/store.rs

Another fixup extracted from #136

Fix: Add EntryHeader::toml_mut()

---

libimagstore/Cargo.toml
libimagstore/src/store.rs

libimagstore: Update dep: version: 1.1.0 -> 2.0.1

---

libimagstore/src/store.rs

Verify toml before write

---

libimagstore/src/error.rs
libimagstore/src/store.rs

Closes #179 
@TheNeikos review pls.

Check whether the StoreId is inside the store

---

README.md

Closes #181 
@TheNeikos and @neithernut , for legal reasons, I want your ACK on this one.

Fix wrong license note in README.md file

---

libimagstore/src/store.rs

Implement Store::retrieve_copy()

---

.travis.yml

Rewrite travis.yml to build all the things

---

libimagstore/Cargo.toml
libimagstore/src/lib.rs
libimagstore/src/store.rs
libimagutil/Cargo.toml
libimagutil/src/key_value_split.rs
libimagutil/src/lib.rs

Regex lazy static

---

doc/src/02000-store.md
doc/src/02010-linking.md
doc/src/04100-lib-link.md

Chapter on how linking to {internal, external} content works.

doc: Add chapter on linking

---

libimagstore/src/lazyfile.rs

Fix: implicitely create directories on file saving

---

doc/src/06020-module-counter.md
imag-counter/Cargo.toml
imag-counter/src/create.rs
imag-counter/src/delete.rs
imag-counter/src/main.rs
imag-counter/src/ui.rs
libimagcounter/Cargo.toml
libimagcounter/src/counter.rs
libimagcounter/src/error.rs
libimagcounter/src/lib.rs
libimagcounter/src/result.rs
libimagstore/src/store.rs
libimagutil/src/trace.rs

Just some boilerplate by now, waiting for #149, #171, #174 and maybe #191.

Imag counter/init

---

libimagutil/src/trace.rs

Add missing newline when tracing.
Closes #240

trace: Add missing newline

---

CONTRIBUTING.md
README.md

This is an update for the `README.md` file, so it lists some more information on this project.
Good advertising and so on, you know...
@TheNeikos , @neithernut please proof-read this! :smile:

Update README to contain more detailed information

---

imag-store/src/ui.rs

Add clap::ArgGroup to rely on clap for mutually exclusive args

---

imag-view/Cargo.toml
imag-view/src/error.rs
imag-view/src/main.rs
imag-view/src/ui.rs
imag-view/src/viewer/mod.rs
imag-view/src/viewer/stdout.rs

Imag view/init

---

imag-counter/src/interactive.rs
imag-counter/src/main.rs
imag-counter/src/ui.rs

Based on #193, will be rebased onto master as soon as #193 is merged.
Opened PR for tracking.

Imag counter/interactive

---

libimagtag/src/exec.rs
libimagtag/src/lib.rs

Add tag helper to execute the CLI spec for an entry

---

libimagstore/src/error.rs
libimagstore/src/store.rs

Add implementation for Store::retrieve_for_module()

---

libimagtag/src/ui.rs

Add helper functions to get names of arguments/subcommands

---

libimagrt/src/configuration.rs
libimagrt/src/runtime.rs

Editor functionality.
Signed-off-by: Kai Sickeler <k.sickeler@gmail.com>

Add editor()

---

libimagtag/Cargo.toml
libimagtag/src/lib.rs
libimagtag/src/tagable.rs

Make tags unique before writing

---

imag-counter/README.md
imag-link/README.md
imag-store/README.md
imag-tag/README.md
imag-view/README.md
libimagcounter/README.md
libimagentryfilter/README.md
libimaglink/README.md
libimagrt/README.md
libimagstore/README.md
libimagtag/README.md
libimagutil/README.md

Per crate readme

---

imag-store/src/ui.rs

This was the fix which should be done by #286 
The arg-group was wrong, not the test.

Remove false grouping from UI

---

libimagentryfilter/Cargo.toml

Update dependency: clap 1.5.5 -> 2.1.1

---

libimagstore/src/store.rs

Remove aspects which were removed in #277

---

libimagutil/src/trace.rs

More missing newline characters.

Add another missing newline character

---

libimagrt/src/logger.rs

logger: Print file and line on debug printing

---

libimaglink/src/internal.rs

Rewrite process_rw_result()
---
It did not cover the aspect that the passed toml `Value` object was an
Array in the first place and assumed that it is an `String` instead,
which caused the function always to return an Result::Err, which was
obviousely buggy.
This is almost a rewrite of the process_rw_result() function which takes
the additional layer (Array(String)) into account and therefor fixes
this issue.

Bug fixes for libimaglink

---

imag-link/src/main.rs

Imag link/zero warnings

---

imag-counter/src/interactive.rs
imag-counter/src/list.rs
imag-counter/src/main.rs

Imag counter/zero warnings

---

imag-view/src/error.rs
imag-view/src/main.rs

Imag view/zero warnings

---

imag-counter/src/main.rs
imag-link/src/main.rs
imag-notes/src/main.rs
imag-store/src/main.rs
imag-tag/src/main.rs
imag-view/src/main.rs

Remove init logging

---

.travis.yml
imag-link/tests/link-test.sh
imag-link/tests/utils.sh
imag-store/tests/001-create_test.sh
imag-store/tests/002-retrieve_test.sh
imag-store/tests/003-delete_test.sh
imag-store/tests/utils.sh
tests/utils.sh

Linking testing.
Includes bash script testing-suite refactoring.

Imag link/testing

---

imag-store/src/create.rs
imag-store/src/delete.rs
imag-store/src/main.rs
imag-store/src/retrieve.rs
imag-store/src/update.rs
imag-store/src/util.rs

Imag store/zero warnings

---

imag-store/src/retrieve.rs
libimagentrylink/src/external.rs
libimagentrylist/src/listers/core.rs
libimagentrylist/src/listers/path.rs
libimagnotes/src/note.rs
libimagstore/src/store.rs

Remove unneeded derefs

---

imag-counter/src/list.rs
imag-counter/src/main.rs
imag-link/src/main.rs
imag-notes/src/main.rs
imag-store/src/create.rs
imag-store/src/delete.rs
imag-store/src/main.rs
imag-store/src/retrieve.rs
imag-store/src/update.rs
imag-tag/src/main.rs
imag-view/src/main.rs
libimagcounter/src/counter.rs
libimagentrylink/src/external.rs
libimagentrylink/src/internal.rs
libimagentrytag/src/tagable.rs
libimagnotes/src/note.rs
libimagrt/src/runtime.rs
libimagstore/src/store.rs
libimagstore/src/storeid.rs

Unwrap err

---

libimagutil/src/trace.rs

Some nicer output for the trace() helpers.

Make trace() output a bit nicer

---

.travis.yml

Add caching for cargo in travis.

Add cargo cache for travis

---

imagrc.toml

Can be used after #387 and #388 are merged.

Add example configuration file

---

imag-link/Cargo.toml
libimagentrylink/Cargo.toml
libimagentrylink/src/external.rs

Updates the `url` dependency and adapts the API changes.

Update dependency: url: 0.5.5 -> 1.1

---

imag-tag/src/main.rs
imag-tag/src/ui.rs

Imag tag/add remove multiple

---

CONTRIBUTING.md

Contributing: Add label explanation

---

libimagentrylist/src/listers/core.rs

Small enhancement for debugging purposes.

Add counter in libimagentrylist::listers::Core

---

libimagentrylink/src/external.rs

Add missing keyword "pub" for Link type

---

libimagstore/src/store.rs

Closes #445 
@TheNeikos review? I know the code is ugly, but this small piece took ~2 hrs to craft, so I just committed it and awaiting review now.

Fix Store::get()

---

imag-tag/src/main.rs

Rewrite UI to use Store::get() which does not implicitely create entries

---

imag-notes/src/main.rs
libimagnotes/src/note.rs

Imag notes/get

---

imag-store/tests/utils.sh

Fix wrong inclusion of utility script functions in test util file.

Fix: sourcing of test-util helper functions fixed

---

libimagstore/src/configuration.rs
libimagstore/src/error.rs
libimagstore/src/store.rs

Targets #169 , though I'm not sure I can implement such a thing.
@TheNeikos should implement this.

Add functions for moving and copying store entries

---

imag-diary/Cargo.toml
imag-diary/src/create.rs
imag-diary/src/delete.rs
imag-diary/src/edit.rs
imag-diary/src/list.rs
imag-diary/src/main.rs
imag-diary/src/ui.rs
imag-diary/src/util.rs
imag-diary/src/view.rs
libimagdiary/src/iter.rs
libimagdiary/src/lib.rs

Diary module based on #309 (libimagdiary).
Currently based on the PR for #309, so must be rebased as soon as #309 is merged.

Imag diary/init

---

doc/Makefile

Generate manpage from doc

---

bin/src/main.rs

fix command finding in imag/bin/src/main.rs

---

libimagstore/src/storeid.rs

@TheNeikos 
Does this make any sense here?

Impl Display for StoreId

---

imag-ref/Cargo.toml
imag-ref/src/main.rs
imag-ref/src/ui.rs

Currently based on #468 (therefor contains commits of it), but will be rebased as soon as #468 is working as expected.

Imag ref/init

---

libimaginteraction/src/ask.rs

Fix bug when newline is in the input

---

imag-view/Cargo.toml

Might close the issue reported in #515

Remove unused dependency: rustbox

---

libimagstorestdhook/src/debug.rs

Print debugging information in debug hook when setting config

---

libimagstore/src/hook/aspect.rs

Add error output in Aspect execution code

---

libimagstore/src/configuration.rs

Fix AspectConfig::get_for() implementation

---

libimagstore/src/store.rs

Add more error levels in hook execution error wrapping

---

imag-ref/src/main.rs

Will be rebased after #468 #497 and #481 are merged, a lot of commits will vanish then.

imag-ref/list

---

libimagrt/src/runtime.rs

Fix: hook registering should be hook-type agnostic

---

libimagstore/src/hook/accessor.rs
libimagstore/src/hook/mod.rs

(and we do not have the possibility to, actually).
Extracted from #486 
@TheNeikos can you review this ... I'm not that familiar with Send/Sync, so it would be better if you would have a close look...

Remove "Sync" trait bound - we don't need to sync between threads here

---

libimagstore/src/hook/error.rs

Add interface for custom error data type

---

libimagerror/src/error_gen.rs

Add setter for custom data for error types

---

libimagstore/src/configuration.rs

Just a quickfix-like fixup of the comment here.

Fix comment how config has to look

---

libimagrt/src/runtime.rs

Change default log level to Warn

---

libimagstore/src/configuration.rs

Make warning more verbose, tell what kind of variable cannot be fetched

---

libimagbookmark/src/lib.rs

Number 1 in a series of seven branches addressing #507.

libimagbookmark: Deny warnings

---

libimaginteraction/src/lib.rs

Number 5 in a series of seven branches addressing #507.

libimaginteraction: Deny warnings

---

libimagref/src/flags.rs
libimagref/src/lib.rs
libimagref/src/lister.rs
libimagref/src/reference.rs

Number 6 in a series of seven branches addressing #507.

libimagref: Deny warnings and fix denied warnings

---

libimagtimeui/src/cli.rs
libimagtimeui/src/lib.rs

Number 7 in a series of seven branches addressing #507.

libimagtimeui: Deny warnings and fix denied

---

libimagrt/src/runtime.rs

Search for imagrc in RTP and not in RTP/store

---

libimagstore/src/store.rs

Implement Debug for FileLockEntry, do not derive it

---

.travis.yml

Quiet travis

---

libimagutil/src/debug_result.rs
libimagutil/src/info_result.rs
libimagutil/src/lib.rs
libimagutil/src/log_result.rs

More to come.
Refactoring could be included in this PR as well.
@asuivelentine do you want to provide some commits for this? Would be a nice training for refactoring for you! :smile: If you want to, let me know!

Add utility to print debugging information while mapping

---

imag-diary/src/create.rs
imag-diary/src/main.rs
imag-diary/src/view.rs

Remove warnings in `imag-diary`

Imag diary/warnings

---

libimagentryfilter/src/builtin/bool_filter.rs
libimagentryfilter/src/builtin/mod.rs

Add BoolFilter

---

README.md

Add contact information including mail and IRC

---

libimagentrylink/src/error.rs
libimagentrylink/src/external.rs
libimagentrylink/src/internal.rs

#576 gets targeted by this PR.

libimagentrylink - unwrap() cleanup

---

imag-store/src/create.rs
imag-store/src/delete.rs
imag-store/src/get.rs
imag-store/src/retrieve.rs
imag-store/src/update.rs

Imag store/refactor unwraps

---

libimagrt/src/runtime.rs

Make arg names publicly available

---

imag-todo/Cargo.toml
libimagtodo/Cargo.toml

imag-todo: Update crate version

---

libimagtodo/src/lib.rs

Addresses #627.
Signed-off-by: Gavin Thomas Claugus <gclaugus@gmail.com>

libimagtodo: Deny warnings

---

.travis.yml

Some small enhancements to the current travis setup.
Should be ready.

Travis small enhancements

---

Makefile

Rewrite Makefile

---

libimagentryselect/Cargo.toml
libimagtimeui/Cargo.toml

@asuivelentine is to blame for this. :smile: 
Funny that it didn't break the build when you introduced these errors.
---
Waiting for #652

Fix dependency spec

---

.travis.yml

We do not yet have a setup for github pages... this one implements it.
I'm not sure whether this succeeds, as we need `sudo` to `pip install` `ghp-import` - lets see how this can be fixed.

Travis gh pages doc

---

libimagstore/src/store.rs

Remove duplication

---

Makefile
README.md

Add install/release target to Makefile

---

libimagutil/src/lib.rs
libimagutil/src/warn_result.rs

Proves useful in one of my follow-up PRs I'm preparing for #667 .

Add libimagutil::warn_result::*

---

tests/utils.sh

Disable debug output in shell-script tests

---

Makefile
README.md

@mario-kr Would be nice if you could review.

Add targets for the imag binary itself

---

libimagstorestdhook/src/linkverify.rs

libimagstorestdhook cleanup

---

libimagstore/src/store.rs

as we do not longer have the concept of store-entry versions

Remove Store::get_all_versions()

---

imag-view/src/editor.rs
imag-view/src/main.rs

#475 
Not sure what I should open? Do I get a path from FLE or do I have to use the content of it and send it to stdin, ....?
```
editor.arg(what).spawn()
````

get default editor

---

libimagdiary/src/is_in_diary.rs
libimagentrylink/src/external.rs
libimagstore/src/storeid.rs

Here go some general cleanup patches for #667

General cleanup for #667

---

imag-diary/src/create.rs
imag-diary/src/delete.rs
imag-diary/src/edit.rs
imag-diary/src/list.rs
imag-diary/src/view.rs
libimagdiary/src/error.rs

Partially targets #615, but not so much as this is just a mini refactoring of `imag-diary` and does not move functionality.

imag-diary/refactor

---

libimagerror/src/trace.rs

Add Result helpers for trace()ing errors

---

libimagstore/src/error.rs
libimagstore/src/store.rs
libimagstore/src/storeid.rs

libimagstore/fix GlobStoreIdIterator

---

libimagstore/src/storeid.rs

Remove StoreId::storified()

---

libimagtodo/Cargo.toml
libimagtodo/src/lib.rs
libimagtodo/src/task.rs

(Waiting on merge of ~~#686~~ #692 )
Add some debug output in `libimagtodo`.
---
Closes #628

libimagtodo: Debug output

---

imag-link/tests/link-test.sh
libimagentrylink/src/internal.rs

imag-link script tests were broken.
And nobody told me. :cry:

Imag link/test fixup

---

libimagstorestdhook/src/vcs/git/config.rs
libimagstorestdhook/src/vcs/git/error.rs
libimagstorestdhook/src/vcs/git/update.rs

Compiles for me, so I'll file it. We can possibly start refactoring some things out here.

libimagstorestdhook: git update hook impl

---

imag-counter/src/interactive.rs
imag-diary/src/create.rs
imag-diary/src/delete.rs
imag-diary/src/edit.rs
imag-diary/src/list.rs
imag-diary/src/view.rs
imag-link/src/main.rs
imag-store/src/delete.rs
imag-store/src/verify.rs
imag-tag/Cargo.toml
imag-tag/src/main.rs

Followup for #695 - use the new helper function whenever possible.

Use warn exit helper

---

bin/Cargo.toml
bin/src/main.rs

Use clap in bin/imag binary.

---

imag-counter/src/list.rs
imag-counter/src/main.rs
imag-diary/src/edit.rs
imag-diary/src/list.rs
imag-link/src/main.rs
imag-notes/Cargo.toml
imag-notes/src/main.rs
imag-store/src/delete.rs
imag-store/src/retrieve.rs
imag-todo/src/main.rs

Closes #714 
I guess there will be a lot of CI errors as I didn't test-compile this at all.

Use result trace helper

---

libimagstore/src/store.rs
libimagstorestdhook/src/vcs/git/create.rs
libimagstorestdhook/src/vcs/git/update.rs
tests/utils.sh

It is not working yet, but I hope that @TheNeikos can tell me what is wrong here.
---
( @TheNeikos see your mail account, I've written a mail how to reproduce the issue I'm experiencing )

libimagstorestdhook: git ci fixes

---

libimagstore/src/storeid.rs

Remove StoreId::is_dir()

---

libimagstore/src/storeid.rs
libimagstorestdhook/src/linkverify.rs

Remove StoreId::is_file()

---

libimagstorestdhook/src/vcs/git/config.rs
libimagstorestdhook/src/vcs/git/create.rs
libimagstorestdhook/src/vcs/git/runtime.rs
libimagstorestdhook/src/vcs/git/update.rs
libimagstorestdhook/src/vcs/git/util.rs

Small enhancement.
The warning output while developing gets annoying :smile:

libimagstorestdhook: gi hooks:t remove unused imports

---

libimagstorestdhook/src/vcs/git/runtime.rs
libimagstorestdhook/src/vcs/git/update.rs

As requested by @mario-kr (and me).
PR for #486

libimagstorestdhook: git: only commit if changed

---

.travis.yml

Try out matrix builds on travis, for a speed up of some things.
But first convert to use the `Makefile` for building the things.

Travis matrix builds

---

libimagstorestdhook/src/vcs/git/error.rs

libimagstorestdhook/git: Remove unused error kinds

---

libimagstore/src/store.rs
libimagstorestdhook/src/vcs/git/runtime.rs

libimagstorestdhook/git: refactor error mapping

---

libimagrt/src/runtime.rs
libimagstorestdhook/src/vcs/git/action.rs
libimagstorestdhook/src/vcs/git/config.rs

libimagstorestdhook/git: fix warn messages

---

libimagstorestdhook/src/vcs/git/delete.rs
libimagstorestdhook/src/vcs/git/update.rs

libimagstorestdhook/git: More debug output

---

libimagstorestdhook/src/vcs/git/config.rs
libimagstorestdhook/src/vcs/git/delete.rs
libimagstorestdhook/src/vcs/git/update.rs

libimagstorestdhook/git: Provide better commit template message, including action and store id

---

imagrc.toml
libimagstorestdhook/src/lib.rs
libimagstorestdhook/src/vcs/git/config.rs
libimagstorestdhook/src/vcs/git/delete.rs
libimagstorestdhook/src/vcs/git/error.rs
libimagstorestdhook/src/vcs/git/runtime.rs
libimagstorestdhook/src/vcs/git/update.rs

PR on #486 
Re-enable the deny of warnings.
Should be rebased after #745 and #748 are merged, IMO.

libimagstorestdhook/git: reenable warning deny

---

libimagstore/src/configuration.rs
libimagstore/src/error.rs
libimagstore/src/store.rs

Tests for running store hooks that succeed.
PR on #698.

libimagstore/store: tests succeeding hook tests

---

.travis.yml
Makefile
imag-link/tests/Makefile
imag-store/tests/Makefile

@neithernut is this a good idea?

Execute tests via Makefile

---

imag-diary/Cargo.toml
imag-diary/src/main.rs
imag-diary/src/view.rs
libimagdiary/Cargo.toml
libimagdiary/src/error.rs
libimagdiary/src/lib.rs
libimagdiary/src/viewer.rs

Closes #615 
I guess more cant be moved to the library, as all other code has commandline processing involved from what I see.

imag-diary: move viewer impl

---

imag-view/src/main.rs
imag-view/src/ui.rs

imag-view: implement default functionality

---

libimagstore/src/store.rs

@TheNeikos am I right that [here](https://github.com/matthiasbeyer/imag/blob/master/libimagstore/src/store.rs#L659) is a negation error?
This test seems to fail because of exactly this negation error I suspect here.
PR on #698.

Libimagstore/store: tests move by id test

---

doc/src/04020-module-tag.md
imag-bookmark/src/ui.rs
imag-ref/Cargo.toml
imag-ref/src/main.rs
imag-ref/src/ui.rs
libimagentrytag/src/ui.rs
libimagutil/Cargo.toml
libimagutil/src/cli_validators.rs
libimagutil/src/lib.rs

Clap validators

---

Makefile

Fix missing [[ on travis

---

libimagstore/src/store.rs

PR on #698 
Adds erroring hooks testing, whether the store behaves correctly.

libimagstore/store: tests erroring hooks

---

libimagstore/src/store.rs

Blocked by #760 
PR on #698 
WIP

libimagstore/store-tests: more succeeding hook tests

---

libimagstore/src/store.rs

libimagstore/store: tests allowed erroring hooks

---

imagrc.toml
libimagrt/src/runtime.rs
libimagstorestdhook/src/vcs/git/action.rs
libimagstorestdhook/src/vcs/git/config.rs
libimagstorestdhook/src/vcs/git/delete.rs
libimagstorestdhook/src/vcs/git/error.rs
libimagstorestdhook/src/vcs/git/mod.rs
libimagstorestdhook/src/vcs/git/store_unload.rs
libimagstorestdhook/src/vcs/git/update.rs

Closes #732.
Commit on drop via store configuration.

libimagstorestdhook/git: commit on drop

---

imagrc.toml
libimaginteraction/Cargo.toml
libimaginteraction/src/error.rs
libimaginteraction/src/lib.rs
libimaginteraction/src/readline.rs

Readline support via the rustyline crate.

libimaginteraction: readline support

---

imag-link/src/main.rs
libimagbookmark/src/collection.rs
libimagentrylink/src/external.rs
libimagentrylink/src/internal.rs

libimagentrylink: iter interface

---

libimagstore/src/file_abstraction.rs
libimagstore/src/store.rs
libimagstore/src/storeid.rs

libimagstore: reduce unwraps

---

default.nix

Fix default.nix syntax

---

libimagentrylink/src/internal.rs

Next step in #802 - more iterators for more fun!
:smile: 
---
Suggestions welcome!

Initial add iterators for link library

---

imag-diary/src/list.rs
libimagmail/src/hasher.rs
libimagref/src/error.rs
libimagref/src/lister.rs
libimagref/src/reference.rs

Resolve some `Result::ok()` calls to not hide the errors anymore.
Closes #811

Resolve hidden errs

---

imag-bookmark/Cargo.toml
libimagbookmark/Cargo.toml

Commits from the 0.2.0 release prep branch which should be imported to master.

Release commits import

---

libimagstore/src/storeid.rs

Impl PartialEq for StoreId

---

imag-link/src/main.rs

Imag link/reduce unwraps

---

libimagentrytag/src/tagable.rs

Remove impl Tagable for FileLockEntry, as Deref{Mut,} does this for us

---

libimagdiary/src/diaryid.rs
libimagdiary/src/error.rs
libimagdiary/src/iter.rs

This is still work in progress, but should fix #778.

[WIP] Use Result for from_storeid

---

imag-mail/Cargo.toml
imag-mail/README.md
imag-mail/src/main.rs
imag-mail/src/ui.rs

Currently based on the PR for `libimagmail` #657 but once working we will rebase this on master and merge independently, I guess.

imag-mail: init

---

libimagentrylink/src/external.rs

Well... :cry: 
At least it _is_ documented.

Fix docu typo

---

bin/build.rs

@mario-kr We don't need this anymore, do we? :smile:

Remove removed crates from compl-gen build script

---

default.nix

Update the dependency list in `default.nix`.

Give the default.nix some love

---

.travis.yml
Makefile
bin/build.rs

Lets see what happens if we move some things out of our travis configuration.

Travis opt

---

imag-link/src/main.rs
imag-link/src/ui.rs

Funny side note:
As the commit history reveals, I wasn't active in this repository for
some time.
I first implemented a solution for this problem in about 50 lines of
code. Then I thought that this could be done way simpler, so I rewrote
it in about 20 lines.
Finally, I noticed that I already have infrastructure for this, so this
two-line patch should fix the problem.
Know your codebase, dude!
---
Closes #841 
@mario-kr could you test?

Fix: Only list internal links here, no external ones

---

README.md
libimagruby/README.md

Updates for the README files.
@mario-kr Would you suggest more README files which could need an update?

Readme updates

---

Cargo.toml

Add missing .imag-documentation to workspace

---

Cargo.toml

Virtual workspaces do only have the workspace key

---

libimagentrymarkdown/src/html.rs
libimagentrymarkdown/src/link.rs
libimagerror/src/error_gen.rs
libimagref/src/reference.rs

Remove warnings from a few crates.

Remove warnings

---

libimagruby/src/store.rs

Impl Store::retrieve_for_module() interface function

---

.travis.yml
Makefile
default.nix
libimagruby/.gitignore
libimagruby/Makefile
libimagruby/Rakefile
libimagruby/ext/Rakefile
libimagruby/imag.gemspec
libimagruby/lib/imag.rb
libimagruby/test/test_entries.rb
libimagruby/test/test_ruby.rb
libimagruby/test/test_store.rb

Reverts matthiasbeyer/imag#871
---
It seems that #871 itself build fine, but after merging in master, things failed.
---
CC @malept

Revert "Ruby build setup"

---

doc/src/05100-lib-ref.md
doc/src/05100-lib-rt.md
doc/src/05100-lib-store-std-hook.md
doc/src/05100-lib-store.md
libimagstorestdhook/README.md

Some long-term todos which should go into the documentation in my opinion.

Libimag todos

---

libimaginteraction/src/ask.rs

This function does not need to be public

---

libimagentryedit/src/edit.rs

We dont need to impl this for FileLockEntry here

---

libimagnotes/src/note.rs

Closes #850 
Lets see whether this compiles.

Remove Tagable implementation for Note

---

libimagstore/src/configuration.rs

Less fold more defresult

---

.travis.yml

Add libruby travis dependency

---

libimagruby/src/entry.rs
libimagruby/src/imag.rs
libimagruby/src/store.rs
libimagruby/src/storeid.rs
libimagstore/src/store.rs

Fix some compiletime warnings.

Fix warnings

---

libimagentrylist/src/listers/line.rs
libimagentrylist/src/listers/path.rs
libimagrt/src/configuration.rs
libimagstore/src/configuration.rs
libimagstore/src/hook/aspect.rs
libimagstore/src/store.rs
libimagutil/src/iter.rs

- Add tests for FoldResult
- Make documentation more explicit
- Assert failure accumulator in test
Submitted-by: Matthew Piziak <matthew.piziak@gmail.com>
Signed-off-by: Matthias Beyer <mail@beyermatthias.de>
---
Closes #898 , #796

Simplify FoldResult implementation

---

libimagruby/src/storeid.rs
libimagstore/src/store.rs
libimagstore/src/storeid.rs
libimagstorestdhook/src/linkverify.rs

Redefine return type of StoreId::exists()

---

libimagutil/src/iter.rs

Remove unused keyword "mut"

---

libimagstore/src/storeid.rs

libimagstore: StoreId tests

---

README.md

Added Tokei badge for displaying LOC

---

libimagstore/Cargo.toml
libimagstore/src/store.rs

Add file-system file locking functionality in the store

---

libimagstore/src/store.rs

Remove hooks more store debugging

---

libimagentrylink/src/internal.rs
libimagerror/src/error_gen.rs
libimagstore/src/error.rs

Remove hooks impl link consistency check in libimagentrylink

---

libimagentrydatetime/src/datetime.rs

Fix header location for datetime values

---

libimagentrytag/Cargo.toml
libimagentrytag/src/lib.rs
libimagentrytag/src/tag.rs

Add clap validator for tag string

---

libimagstore/src/file_abstraction.rs

Remove "TODO"-comment

---

libimagstore/src/storeid.rs

A nice extraction from another PR.

Add fn StoreId::local_push() for altering the local part of a StoreId

---

libimagstore/src/store.rs

Add Store::entries()

---

libimagstore/src/file_abstraction/inmemory.rs

Remove unnecessary clone() call

---

.travis.yml
imag-diary/src/main.rs
libimagbookmark/Cargo.toml
libimagbookmark/src/lib.rs
libimagcounter/src/lib.rs
libimagdiary/Cargo.toml
libimagdiary/src/lib.rs
libimagstore/src/lib.rs

I don't remember why we disabled this, actually.
Closes #979

Build with rust stable/beta/nightly

---

Cargo.toml
doc/src/05100-lib-timetrack.md
libimagtimetrack/Cargo.toml
libimagtimetrack/README.md
libimagtimetrack/src/constants.rs
libimagtimetrack/src/error.rs
libimagtimetrack/src/event.rs
libimagtimetrack/src/eventstore.rs
libimagtimetrack/src/iter/create.rs
libimagtimetrack/src/iter/get.rs
libimagtimetrack/src/iter/mod.rs
libimagtimetrack/src/iter/setendtime.rs
libimagtimetrack/src/iter/storeid.rs
libimagtimetrack/src/iter/tag.rs
libimagtimetrack/src/lib.rs
libimagtimetrack/src/result.rs
libimagtimetrack/src/tag.rs

imag-timetrack / libimagtimetrack

---

imag-link/src/main.rs

Closes #981 
Although this fixes the panic, we have another issue now. The entry looks like this after the removal of the link:
```
---
[imag]
links = []
version = "0.3.0"
---
EXAMPLE!--
EXAMPLE!
```
which is not valid.
I'm not sure whether this is a bug in the store...

Imag link/fix panic

---

default.nix

Remove bundler

---

libimagstore/src/store.rs

Related to #1003 
Does not close the issue mentioned above, because this only reimplements the iterator to fix buggy behaviour.
This PR is ready, though.

Reimplement GlobStoreIdIterator

---

README.md

Updates the readme for the 0.3.0 release.
Closes #891

Update for beeing up-to-date

---

libimagstore/src/storeid.rs

I found this in an old branch, unmerged. Could be useful some day.

Add StoreId::is_in_collection()

---

bin/Cargo.toml
bin/src/main.rs

The patch also contains some more minor fixes and cleanup.

Rewrite imag binary without parallelization stuff

---

doc/src/09000-todos.md

I guess this would be a welcoming thing, right?

Add todo: Rewrite libimagerror with chain-error crate

---

.imag-documentation/Cargo.toml

Fix documentation version number for next release

---

bin/domain/imag-diary/src/create.rs
bin/domain/imag-diary/src/delete.rs
bin/domain/imag-diary/src/edit.rs
bin/domain/imag-diary/src/list.rs
bin/domain/imag-diary/src/view.rs
lib/domain/libimagdiary/src/diary.rs
lib/domain/libimagdiary/src/entry.rs
lib/domain/libimagdiary/src/error.rs
lib/domain/libimagdiary/src/is_in_diary.rs
lib/domain/libimagdiary/src/iter.rs
lib/domain/libimagdiary/src/viewer.rs

Everything as trait in libimagdiary, pls!
WIP.

libimagdiary: extension as trait

---

Cargo.toml
doc/src/09020-changelog.md
lib/entry/libimagentrygps/Cargo.toml
lib/entry/libimagentrygps/src/entry.rs
lib/entry/libimagentrygps/src/error.rs
lib/entry/libimagentrygps/src/lib.rs
lib/entry/libimagentrygps/src/result.rs
lib/entry/libimagentrygps/src/types.rs

I guess I'm already done here.
The types can be improved to have some convenience functionality, but for the first step, this it is.

libimagentrygps: init

---

bin/core/imag-store/Cargo.toml
bin/core/imag-store/src/create.rs
bin/core/imag-store/src/delete.rs
bin/core/imag-store/src/main.rs

Imag store/tests

---

lib/entry/libimagentrymarkdown/Cargo.toml
lib/entry/libimagentrymarkdown/src/error.rs
lib/entry/libimagentrymarkdown/src/lib.rs
lib/entry/libimagentrymarkdown/src/link.rs
lib/entry/libimagentrymarkdown/src/processor.rs

libimagentrymarkdown: md links to imag links

---

bin/core/imag/Cargo.toml
bin/core/imag/src/main.rs
imagrc.toml

Compiles, but not yet tested.
Anyone volunteering? @mario-kr ? :smile:

Implement aliases for imag binary

---

lib/core/libimagrt/src/error.rs
lib/core/libimagrt/src/logger.rs

Some optimizations of the error handling in `libimagrt`.

libimagrt: error optimizations

---

lib/core/libimagstore/src/error.rs
lib/core/libimagstore/src/store.rs
lib/core/libimagstore/src/storeid.rs
lib/entry/libimagentrycategory/src/register.rs

This PR optimizes the error setup in the store, removing some errors, adding context information to others.

libimagstore: Optimize errors

---

lib/core/libimagstore/src/iter.rs
lib/core/libimagstore/src/lib.rs

Nice iterators for the Store. Really just basic things here.

libimagstore: iter

---

bin/domain/imag-notes/src/main.rs
doc/src/09020-changelog.md
lib/domain/libimagnotes/src/iter.rs
lib/domain/libimagnotes/src/note.rs
lib/domain/libimagnotes/src/notestore.rs
lib/domain/libimagnotes/src/notestoreid.rs
lib/entry/libimagentryannotation/src/annotation_fetcher.rs

Missed with the last refactoring.

libimagnotes: Do not wrap store types.

---

lib/core/libimagstore/src/store.rs

Do not insert the links array in the core header

---

bin/core/imag-tag/src/main.rs
bin/core/imag-tag/src/ui.rs

Transform UI to use positional args

---

lib/core/libimagstore/src/file_abstraction/fs.rs
lib/core/libimagstore/src/file_abstraction/inmemory.rs
lib/core/libimagstore/src/file_abstraction/mod.rs
lib/core/libimagstore/src/file_abstraction/stdio/mod.rs
lib/core/libimagstore/src/file_abstraction/stdio/out.rs
lib/core/libimagstore/src/store.rs

libimagstore: move_by_id() should check FS

---

bin/core/imag-tag/src/main.rs
lib/core/libimagstore/src/store.rs
lib/entry/libimagentrytag/src/tagable.rs

Do not use "imag" namespace in header

---

bin/core/imag/src/main.rs
doc/src/09020-changelog.md

Ensure that all arguments are passed to the subcommand

---

lib/core/libimagstore/src/store.rs

Serialize TOML pretty

---

lib/domain/libimagdiary/src/is_in_diary.rs

Base IsInDiary::is_in_diary() on StoreId::is_in_collection()

---

lib/core/libimagstore/src/store.rs

This changes the internal GlobStoreIdIterator to return Result<StoreId>,
which gives us the possibility to aggregate errors in the
Store::retrieve_for_module() function and return them instead of tracing
them from the store.
The changes the internals to actually fetch the whole list of storeids,
which is unfortunate of course, but changing the interface is not an
option here, in my opinion.
At least we're only aggregating pathes, so the memory usage is pretty
low here.
---
Closes #1003

Return glob errors instead of tracing internally

---

lib/entry/libimagentrylink/src/internal.rs

Fixes a critical typo I just spotted.
This could've blow up really badly!

Fix: critical typo

---

lib/entry/libimagentrylink/src/internal.rs

libimagentrylink: consistency check fix

---

Cargo.toml
bin/core/imag-gps/Cargo.toml
bin/core/imag-gps/src/main.rs
bin/core/imag-gps/src/ui.rs
doc/src/04020-module-gps.md
lib/entry/libimagentrygps/src/entry.rs

Blocked by/Needs patches from #1103

imag-gps: init

---

lib/entry/libimagentrylink/src/internal.rs

Add test for testing annotation

---

lib/entry/libimagentryref/src/refstore.rs

Add function to get all references from a `RefStore`

Add RefStore::all_references()

---

.travis.yml

We don't need these things anymore I guess...

Cleanup travis

---

lib/core/libimagstore/src/file_abstraction/fs.rs
lib/core/libimagstore/src/store.rs

libimagstore: fix move

---

Cargo.toml
bin/core/imag-annotate/Cargo.toml
bin/core/imag-annotate/src/main.rs
bin/core/imag-annotate/src/ui.rs
doc/src/09020-changelog.md
lib/entry/libimagentryannotation/src/annotateable.rs

Waiting for #1129 to be merged, as this one is based on #1129.
Closes #687

Imag annotate/init

---

imagrc.toml
lib/etc/libimaginteraction/Cargo.toml
lib/etc/libimaginteraction/src/format.rs
lib/etc/libimaginteraction/src/lib.rs

libimaginteraction: Add more helpers for handlebars

---

bin/core/imag-ref/src/main.rs
lib/entry/libimagentryref/src/refstore.rs

Closes #1140
Ready but untested.

libimagentryref: abbrev hash

---

bin/core/imag-annotate/Cargo.toml
bin/core/imag-store/Cargo.toml

:cry: missed with last update somehow.

Fix missed version updates

---

lib/core/libimagstore/src/store.rs

Remove accidentially slipped-in println

---

lib/core/libimagrt/src/logger.rs

Formerly, the --debug flag was ignores. This change overrides the
logging with the CLI specified logging if it was provided.
If --debug was provided, the logging is set to debugging, if --verbose
was provided info logging is used.

Fix: Overide logging with --debug

---

bin/core/imag/src/main.rs
lib/core/libimagrt/src/logger.rs
lib/core/libimagrt/src/runtime.rs

Remove override functionality for logging formats

---

Cargo.toml
bin/core/imag-diagnostics/Cargo.toml
bin/core/imag-diagnostics/src/main.rs
bin/core/imag-diagnostics/src/ui.rs
doc/src/09020-changelog.md

Imag diagnostics/init

---

bin/core/imag-store/src/verify.rs
lib/core/libimagstore/src/store.rs

Move verify implementation from Store to CLI interface

---

doc/src/09020-changelog.md
lib/core/libimagrt/src/runtime.rs

Try to get RTP from IMAG_RTP

---

.travis.yml
lib/core/libimagstore/src/util.rs

We did not test with all features enabled... Wonder how this could have happened.

Travis all

---

lib/entry/libimagentrylist/src/listers/table.rs

One small fix for the TableLister.

TableLister: If configured with index, also print index row

---

lib/core/libimagstore/src/store.rs

Don't know how this could happen.

Remove accidentially slipped-in println!()

---

Cargo.toml
doc/src/04020-module-habit.md
doc/src/05100-lib-habit.md
lib/domain/libimaghabit/Cargo.toml
lib/domain/libimaghabit/README.md
lib/domain/libimaghabit/src/error.rs
lib/domain/libimaghabit/src/habit.rs
lib/domain/libimaghabit/src/instance.rs
lib/domain/libimaghabit/src/iter.rs
lib/domain/libimaghabit/src/lib.rs
lib/domain/libimaghabit/src/result.rs
lib/domain/libimaghabit/src/store.rs
lib/domain/libimaghabit/src/util.rs

libimaghabit: init

---

lib/domain/libimaghabit/src/habit.rs

Some refactorings for the API of libimaghabit.

libimaghabit: API cleanup

---

doc/src/00000.md
doc/src/09000-todos.md
doc/src/09020-changelog.md
lib/etc/libimagnotification/Cargo.toml
scripts/release.sh

Integrate the release back into master.

V0.5.0 branch

---

lib/core/libimagrt/src/runtime.rs
lib/core/libimagstore/Cargo.toml
lib/core/libimagstore/src/configuration.rs
lib/core/libimagstore/src/error.rs
lib/core/libimagstore/src/lib.rs
lib/core/libimagstore/src/store.rs
lib/domain/libimagtimetrack/src/iter/mod.rs
lib/entry/libimagentrycategory/src/register.rs
lib/entry/libimagentrydatetime/src/datetime.rs
lib/entry/libimagentrygps/src/entry.rs
lib/entry/libimagentrylink/src/external.rs
lib/entry/libimagentrylink/src/internal.rs
lib/entry/libimagentrymarkdown/src/processor.rs

libimagstore: remove config

---

Cargo.toml
bin/domain/imag-log/Cargo.toml
bin/domain/imag-log/README.md
bin/domain/imag-log/src/main.rs
bin/domain/imag-log/src/ui.rs
doc/src/04020-module-log.md
imagrc.toml

imag-log: init

---

Cargo.toml
bin/core/imag-init/Cargo.toml
bin/core/imag-init/README.md
bin/core/imag-init/src/main.rs
bin/core/imag-init/src/ui.rs
doc/src/04020-module-init.md

imag-init: initial import

---

scripts/hooks/commit-msg.checkstyle.sh
scripts/hooks/pre-push.fixup-warn.sh
scripts/hooks/pre-push.protect-master.sh
scripts/signed-off-by-in-branch.sh

Some cleanup patches for the hook scripts and two new scripts.
I guess I will test them a bit before merging.

Hook scripts

---

TODO.md

Remove dead TODO link

---

.travis.yml

I guess this will fail now, because rustc 1.23.0 will be released tomorrow...

Rustc update

---

lib/domain/libimagdiary/src/diary.rs
lib/domain/libimagdiary/src/diaryid.rs

Add second-support in libimagdiary

---

bin/domain/imag-bookmark/src/main.rs
doc/src/09020-changelog.md
lib/domain/libimagbookmark/src/collection.rs
lib/domain/libimagbookmark/src/error.rs

libimagdiary: Do not wrap store types

---

Cargo.toml
doc/src/05100-lib-entryutil.md
doc/src/09020-changelog.md
lib/domain/libimagcontact/Cargo.toml
lib/domain/libimagcontact/src/contact.rs
lib/domain/libimagcontact/src/error.rs
lib/domain/libimagcontact/src/lib.rs
lib/domain/libimagcontact/src/store.rs
lib/domain/libimaghabit/Cargo.toml
lib/domain/libimaghabit/src/error.rs
lib/domain/libimaghabit/src/habit.rs
lib/domain/libimaghabit/src/instance.rs
lib/domain/libimaghabit/src/lib.rs
lib/entry/libimagentryannotation/Cargo.toml
lib/entry/libimagentryannotation/src/annotateable.rs
lib/entry/libimagentryannotation/src/error.rs
lib/entry/libimagentryannotation/src/lib.rs
lib/entry/libimagentryref/Cargo.toml
lib/entry/libimagentryref/src/error.rs
lib/entry/libimagentryref/src/lib.rs
lib/entry/libimagentryref/src/reference.rs
lib/entry/libimagentryref/src/refstore.rs
lib/entry/libimagentryutil/Cargo.toml
lib/entry/libimagentryutil/README.md
lib/entry/libimagentryutil/src/error.rs
lib/entry/libimagentryutil/src/isa.rs
lib/entry/libimagentryutil/src/lib.rs

Utilities for working with `libimagstore::store::Entry` objects.
Very WIP, oh so experimental!

libimagentryutil: init

---

default.nix

Add libtool in default.nix

---

bin/domain/imag-timetrack/src/list.rs
bin/domain/imag-timetrack/src/main.rs

imag-timetrack: default command

---

bin/domain/imag-timetrack/Cargo.toml
bin/domain/imag-timetrack/src/list.rs
bin/domain/imag-timetrack/src/main.rs
doc/src/09020-changelog.md

Change list command to use a table for output

---

.gitignore
.travis.yml
README.md
bin/core/imag-annotate/src/main.rs
bin/core/imag-diagnostics/src/main.rs
bin/core/imag-gps/src/main.rs
bin/core/imag-link/src/main.rs
bin/core/imag-mv/src/main.rs
bin/core/imag-store/src/delete.rs
bin/core/imag-store/src/retrieve.rs
bin/core/imag-view/src/main.rs
bin/domain/imag-contact/src/main.rs
bin/domain/imag-contact/src/util.rs
bin/domain/imag-notes/src/main.rs
bin/domain/imag-timetrack/Cargo.toml
bin/domain/imag-timetrack/src/main.rs
bin/domain/imag-timetrack/src/stop.rs
bin/domain/imag-todo/src/main.rs
doc/default.nix
doc/src/09010-contributing.md
doc/src/09020-changelog.md
lib/core/libimagerror/src/trace.rs
lib/core/libimagstore/src/store.rs
lib/entry/libimagentrycategory/src/register.rs
lib/entry/libimagentrylink/src/internal.rs
scripts/commit-template
scripts/new-crate.sh

Long-living minor patches (mostly infrastructure patches) branch. Integrates #1204 for example.
To be merged right before the 0.6.0 release.

Minor patches

---

bin/core/imag-diagnostics/src/main.rs
bin/core/imag-grep/src/main.rs
lib/core/libimagstore/src/iter.rs
lib/core/libimagstore/src/store.rs
lib/core/libimagstore/src/storeid.rs
lib/domain/libimaghabit/src/iter.rs
lib/entry/libimagentrylink/src/internal.rs
lib/entry/libimagentrymarkdown/src/processor.rs

Some improvements to the Iterator API of libimagstore.
As this API is not yet used that much, these changes do not affect much code outside libimagstore.

libimagstore: improve iterator extensions

---

lib/core/libimagstore/src/storeid.rs
lib/entry/libimagentryutil/Cargo.toml
lib/entry/libimagentryutil/src/isincollection.rs
lib/entry/libimagentryutil/src/iter.rs

Add utilities for filtered iterators.
Maybe we can generalize that and put it into the `filters` crate?

libimagentryutil: filtered iterators

---

bin/domain/imag-notes/Cargo.toml
bin/domain/imag-notes/src/main.rs
lib/domain/libimagnotes/src/error.rs
lib/domain/libimagnotes/src/notestore.rs

Fix imag-notes list errors

---

bin/domain/imag-log/src/main.rs

Do not list entries which are not "log" entries

---

bin/domain/imag-log/src/main.rs

Do not put a leading space in the log

---

bin/core/imag-mv/Cargo.toml
bin/core/imag-mv/src/main.rs

imag-mv: Fix links after moving entry

---

doc/src/09020-changelog.md

Add missing changelog entries

---

doc/src/01000-intro.md
doc/src/01010-architecture.md

Doc overhaul

---

bin/core/imag-init/src/main.rs
bin/domain/imag-contact/Cargo.toml
bin/domain/imag-habit/Cargo.toml
bin/domain/imag-mail/Cargo.toml
doc/Makefile
doc/src/00000.md
doc/src/09020-changelog.md
lib/domain/libimagcontact/Cargo.toml
lib/domain/libimaghabit/Cargo.toml
lib/entry/libimagentryannotation/Cargo.toml
lib/entry/libimagentrygps/Cargo.toml
lib/etc/libimagnotification/Cargo.toml
lib/etc/libimagutil/Cargo.toml
scripts/release.sh

* Add new libraries/binaries to release script

Prepare 0.6.0 release

---

bin/core/imag-grep/src/main.rs

Do not print stats when listing files with matches

---

bin/core/imag/src/main.rs

Add subcommand "help"

---

bin/core/imag/src/main.rs

Sort commands alphabetically

---

bin/domain/imag-log/src/ui.rs

Alias subcommand "show" to "list"

---

bin/core/imag-annotate/src/main.rs
bin/core/imag-edit/src/main.rs
bin/core/imag-gps/src/main.rs
bin/core/imag-link/src/main.rs
bin/core/imag-ref/src/main.rs
bin/domain/imag-contact/src/main.rs
bin/domain/imag-habit/src/main.rs
bin/domain/imag-log/src/main.rs

Do not print "Ok" after successful execution

---

lib/core/libimagerror/src/iter.rs

This iterator exits on the first Err(_)
Will not be in 0.6.0 ... we need to also use this before merging it.

Add TraceIterator::trace_unwrap_exit()

---

.travis.yml
scripts/license-headers-updated

Closes #1269 
Should fail, but succeed when rebased with #1268 merged.

License header checker

---

bin/core/imag-annotate/Cargo.toml
bin/core/imag-diagnostics/Cargo.toml
bin/core/imag-gps/Cargo.toml
bin/core/imag-grep/Cargo.toml
bin/core/imag-init/Cargo.toml
bin/core/imag-link/Cargo.toml
bin/core/imag-mv/Cargo.toml
bin/core/imag-ref/Cargo.toml
bin/core/imag-store/Cargo.toml
bin/core/imag-tag/Cargo.toml
bin/core/imag-view/Cargo.toml
bin/core/imag/Cargo.toml
bin/domain/imag-bookmark/Cargo.toml
bin/domain/imag-contact/Cargo.toml
bin/domain/imag-diary/Cargo.toml
bin/domain/imag-habit/Cargo.toml
bin/domain/imag-log/Cargo.toml
bin/domain/imag-mail/Cargo.toml
bin/domain/imag-notes/Cargo.toml
bin/domain/imag-timetrack/Cargo.toml
bin/domain/imag-todo/Cargo.toml
lib/core/libimagrt/Cargo.toml
lib/entry/libimagentryfilter/Cargo.toml
lib/entry/libimagentrylist/Cargo.toml
lib/entry/libimagentrytag/Cargo.toml
lib/etc/libimaginteraction/Cargo.toml
lib/etc/libimagtimeui/Cargo.toml

Enable clap "color" and "suggestions" feature for all commandline crates.

Clap features

---

lib/core/libimagstore/src/store.rs

Prettify Store debug output implementation

---

bin/core/imag-link/src/main.rs

Without this check, linking an entry with itself yields the following
error:
ERROR[   1]: Entry is already borrowed: StoreId { base: Some("/home/m/.imag/store"), id: "notes/test" }
ERROR[   2]: Error when calling retrieve() -- caused:
ERROR[   3]: Error when calling get()
Which is semantically correct, but the user may get confused by that.
Instead, we print a nice error message that the entry cannot be linked
to itself.
This is not fixed in libimagentrylink itself, because libimagentrylink
cannot be called for the same entry.
If this would be possible, we would pass two `Entry` objects
mutably to the link functionality routines. This is not possible with
Rusts borrow semantics and therefor yields above error.
---
Closes #1250

Do not allow linking with entry itself

---

bin/core/imag-annotate/src/main.rs
bin/core/imag-diagnostics/src/main.rs
bin/core/imag-gps/src/main.rs
bin/core/imag-grep/src/main.rs
bin/core/imag-init/Cargo.toml
bin/core/imag-init/src/main.rs
bin/core/imag-link/src/main.rs
bin/core/imag-store/src/ids.rs
bin/core/imag-store/src/retrieve.rs
bin/core/imag-tag/src/main.rs
bin/core/imag/src/main.rs
bin/domain/imag-bookmark/src/main.rs
bin/domain/imag-contact/src/main.rs
bin/domain/imag-diary/src/main.rs
bin/domain/imag-habit/src/main.rs
bin/domain/imag-log/src/main.rs
bin/domain/imag-mail/src/main.rs
bin/domain/imag-notes/src/main.rs
bin/domain/imag-timetrack/src/day.rs
bin/domain/imag-timetrack/src/month.rs
bin/domain/imag-timetrack/src/week.rs
bin/domain/imag-timetrack/src/year.rs
bin/domain/imag-todo/src/main.rs
lib/core/libimagerror/src/exit.rs
lib/core/libimagerror/src/io.rs
lib/core/libimagerror/src/lib.rs

Closes #1291
Some refactoring involved.

Fix broken pipes

---

lib/domain/libimagdiary/Cargo.toml
lib/domain/libimagdiary/src/diary.rs
lib/domain/libimagdiary/src/entry.rs
lib/domain/libimagdiary/src/error.rs
lib/domain/libimagdiary/src/lib.rs

libimagdiary: Add "isflag" support

---

bin/core/imag-init/Cargo.toml
bin/core/imag-init/src/main.rs
bin/core/imag-init/src/ui.rs

That was not added in imag-init.

Use the make_imag_version!() helper

---

lib/domain/libimagtodo/Cargo.toml

Hey
Updating this crate to 0.6 since the new release is out. There are no further changes required.

Update uuid to 0.6

---

bin/domain/imag-diary/src/create.rs
bin/domain/imag-diary/src/util.rs
doc/src/09020-changelog.md

imag diary: "daily" support + Fixes for other timed entries

---

bin/core/imag-annotate/src/main.rs
bin/core/imag-diagnostics/src/main.rs
bin/core/imag-gps/src/main.rs
bin/core/imag-grep/src/main.rs
bin/core/imag-ids/src/main.rs
bin/core/imag-init/src/main.rs
bin/core/imag-link/src/main.rs
bin/core/imag-store/src/retrieve.rs
bin/core/imag-tag/src/main.rs
bin/domain/imag-bookmark/src/main.rs
bin/domain/imag-contact/src/create.rs
bin/domain/imag-contact/src/main.rs
bin/domain/imag-diary/src/list.rs
bin/domain/imag-diary/src/main.rs
bin/domain/imag-habit/src/main.rs
bin/domain/imag-log/src/main.rs
bin/domain/imag-mail/src/main.rs
bin/domain/imag-notes/src/main.rs
bin/domain/imag-timetrack/src/day.rs
bin/domain/imag-timetrack/src/list.rs
bin/domain/imag-timetrack/src/month.rs
bin/domain/imag-timetrack/src/week.rs
bin/domain/imag-timetrack/src/year.rs
bin/domain/imag-todo/src/main.rs
lib/core/libimagrt/Cargo.toml
lib/core/libimagrt/src/io.rs
lib/core/libimagrt/src/lib.rs
lib/core/libimagrt/src/runtime.rs

libimagrt: provide io

---

lib/core/libimagrt/src/io.rs
lib/core/libimagrt/src/runtime.rs

libimagrt: locked io

---

bin/core/imag-link/src/main.rs
bin/core/imag-store/src/create.rs
bin/core/imag-store/src/delete.rs
bin/core/imag-tag/src/main.rs
lib/core/libimagstore/src/file_abstraction/mod.rs
lib/core/libimagstore/src/file_abstraction/stdio/mapper/json.rs
lib/core/libimagstore/src/store.rs

Replace hard coded version strings with compiletime env

---

lib/core/libimagrt/src/runtime.rs

When we merged the changes in libimagrt so that it automatically detects
whether stdin/stdout is a TTY and provides the user with stderr in case
stdout is not a TTY, we forgot that things like
imag foo | grep bar
becomes impossible with that, because imag detects that stdout is not a
tty and automatically uses stderr for output.
But in this case, we don't want that. The output has to be stdout in
this case.
With this change, we have a flag in the runtime ("--pipe-magic" or "-P",
globally available) which turns on "pipe magic".
The expected behaviour is the following, if "-P" is passed:
* If stdout is a TTY, we print to stdout
* If stdout is not a TTY, we print to stderr
* If stdin is not a TTY, we do not provide it
If "-P" is not passed, we allow the user of libimagrt to use stdin for …

Implement pipe magic in libimagrt

---

lib/domain/libimagcontact/src/error.rs
lib/domain/libimagcontact/src/store.rs

Change `libimagcontact` to generate the unique hash for an entry from its `UID` in the vcard object.

Change ref creation to use UID from vcard object

---

bin/domain/imag-contact/Cargo.toml
bin/domain/imag-contact/src/main.rs
bin/domain/imag-contact/src/ui.rs
lib/domain/libimagcontact/Cargo.toml
lib/domain/libimagcontact/src/deser.rs
lib/domain/libimagcontact/src/lib.rs

With these patches, `imag-contact` can print the output as JSON.

libimagcontact/imag-contact: json output support

---

lib/domain/libimagnotes/src/error.rs
lib/domain/libimagnotes/src/note.rs
lib/domain/libimagnotes/src/notestore.rs

Simplify error handling by using linking feature of error-chain

---

bin/core/imag-edit/src/main.rs
bin/core/imag-edit/src/ui.rs
doc/src/09020-changelog.md

imag-edit: ids from stdin

---

doc/src/09020-changelog.md
lib/core/libimagrt/src/runtime.rs

libimagentryedit: fix editor stdinerr inherit

---

bin/core/imag/src/main.rs

Part of, but does not fix, #1341

Inherit stdio to child process

---

bin/core/imag-ids/src/main.rs
doc/src/09020-changelog.md

imag-ids: prefix printing off by default

---

lib/entry/libimagentryref/src/reference.rs
lib/entry/libimagentryref/src/refstore.rs

Extracted from #1295 
Blocked until we tested #1295 and know it works as expected.

Provide Ref::make_ref() for making a ref out of an existing entry

---

lib/domain/libimaghabit/src/habit.rs

Add helper to check whether an instance exists for a date

---

lib/core/libimagstore/src/store.rs

Fix: Store::create() should fail if the entry exists

---

bin/core/imag-init/src/main.rs

Closes #1362 
Thanks to zorzar on IRC!

Fix: Create store directory as well

---

bin/core/imag-edit/src/main.rs
bin/core/imag-edit/src/ui.rs
lib/entry/libimagentryedit/Cargo.toml
lib/entry/libimagentryedit/src/edit.rs
lib/entry/libimagentryedit/src/error.rs
lib/entry/libimagentryedit/src/lib.rs

imag-edit / libimagentryedit: edit header support

---

bin/core/imag-link/Cargo.toml
bin/core/imag-link/src/main.rs
bin/core/imag-link/src/ui.rs

imag-link: Do table output by default

---

.travis.yml

Reverts matthiasbeyer/imag#1361
After some more discussion in the thread linked in the original PR, I am not sure about whether this actually does what I expect.
I'm so insecure, waaaaah! :sob:

Revert "Remove "build" job to speed up travis builds"

---

lib/core/libimagrt/src/error.rs
lib/core/libimagrt/src/runtime.rs
lib/entry/libimagentryedit/src/edit.rs

libimagrt: Pass /dev/tty as stdin to editor

---

bin/core/imag-diagnostics/src/main.rs
bin/core/imag-link/src/main.rs
bin/core/imag-store/src/retrieve.rs
bin/core/imag-tag/src/main.rs
lib/core/libimagstore/src/error.rs
lib/core/libimagstore/src/file_abstraction/fs.rs
lib/core/libimagstore/src/store.rs
lib/entry/libimagentryedit/src/edit.rs
lib/entry/libimagentrymarkdown/src/processor.rs
lib/entry/libimagentryview/src/builtin/editor.rs
lib/entry/libimagentryview/src/error.rs

Because serializing might fail.
---
Closes #1364

Fix: Entry::to_str() should return Result<_>

---

bin/core/imag-annotate/src/main.rs
bin/core/imag-gps/src/main.rs
bin/core/imag-link/src/main.rs
bin/core/imag-ref/src/main.rs
bin/core/imag-store/src/main.rs
bin/core/imag-tag/src/main.rs
bin/domain/imag-bookmark/src/main.rs
bin/domain/imag-contact/src/main.rs
bin/domain/imag-diary/src/main.rs
bin/domain/imag-habit/src/main.rs
bin/domain/imag-log/src/main.rs
bin/domain/imag-mail/src/main.rs
bin/domain/imag-notes/src/main.rs
bin/domain/imag-timetrack/src/main.rs
bin/domain/imag-todo/src/main.rs
doc/src/09020-changelog.md
lib/core/libimagrt/src/runtime.rs

libimagrt: Handle unknown subcommand

---

bin/domain/imag-contact/src/ui.rs

Changelog pushed to `minor` branch.

imag-contact: Add format argument

---

bin/core/imag-view/src/main.rs
bin/core/imag-view/src/ui.rs
imagrc.toml

imag-view: Add support for viewing multiple entries

---

bin/domain/imag-contact/src/main.rs
bin/domain/imag-contact/src/ui.rs

imag-contact: Add functionality to find contacts and print the storeid/file path

---

bin/core/imag-view/src/main.rs
bin/core/imag-view/src/ui.rs

imag-view: Add support for piping entry ids into command

---

bin/core/imag-grep/src/main.rs

Fix missing counting

---

lib/domain/libimagdiary/src/viewer.rs

Fix: view entries sorted

---

bin/domain/imag-diary/src/list.rs

Fix: List ids sorted

---

bin/core/imag-annotate/Cargo.toml
bin/core/imag-diagnostics/Cargo.toml
bin/core/imag-edit/Cargo.toml
bin/core/imag-gps/Cargo.toml
bin/core/imag-grep/Cargo.toml
bin/core/imag-ids/Cargo.toml
bin/core/imag-init/Cargo.toml
bin/core/imag-link/Cargo.toml
bin/core/imag-mv/Cargo.toml
bin/core/imag-ref/Cargo.toml
bin/core/imag-store/Cargo.toml
bin/core/imag-tag/Cargo.toml
bin/core/imag-view/Cargo.toml
bin/core/imag/Cargo.toml
bin/domain/imag-bookmark/Cargo.toml
bin/domain/imag-contact/Cargo.toml
bin/domain/imag-diary/Cargo.toml
bin/domain/imag-habit/Cargo.toml
bin/domain/imag-log/Cargo.toml
bin/domain/imag-mail/Cargo.toml
bin/domain/imag-notes/Cargo.toml
bin/domain/imag-timetrack/Cargo.toml
bin/domain/imag-todo/Cargo.toml
lib/core/libimagrt/Cargo.toml
lib/entry/libimagentryfilter/Cargo.toml
lib/entry/libimagentrytag/Cargo.toml
lib/etc/libimaginteraction/Cargo.toml
lib/etc/libimagtimeui/Cargo.toml

* Update clap version specification
* Use clap with "wrap_help" feature

Clap text wrap

---

bin/core/imag-annotate/src/main.rs
bin/core/imag-store/src/main.rs
bin/core/imag-tag/src/main.rs
bin/core/imag/src/main.rs
bin/domain/imag-contact/src/create.rs
bin/domain/imag-diary/src/main.rs
bin/domain/imag-log/src/main.rs
bin/domain/imag-mail/src/main.rs
bin/domain/imag-notes/src/main.rs
bin/domain/imag-timetrack/src/main.rs
bin/domain/imag-todo/src/main.rs
lib/domain/libimaghabit/src/lib.rs
lib/domain/libimaglog/src/lib.rs
lib/entry/libimagentrygps/src/lib.rs
lib/etc/libimagnotification/src/lib.rs

Crate lints

---

Cargo.toml
doc/src/05100-lib-wiki.md
lib/domain/libimagwiki/Cargo.toml
lib/domain/libimagwiki/README.md
lib/domain/libimagwiki/src/entry.rs
lib/domain/libimagwiki/src/error.rs
lib/domain/libimagwiki/src/lib.rs
lib/domain/libimagwiki/src/store.rs
lib/domain/libimagwiki/src/wiki.rs
scripts/release.sh

libimagwiki: init

---

bin/domain/imag-diary/src/list.rs

Fix: Use full storeid when listing

---

lib/core/libimagrt/src/runtime.rs

Suggest imag-init if no config is found

---

bin/domain/imag-log/Cargo.toml
bin/domain/imag-log/src/main.rs
lib/domain/libimagdiary/src/diaryid.rs

Fix: imag-log show should order by datetime

---

scripts/branch-contains-no-tmp-commits

Fix checker script for travis

---

bin/domain/imag-mail/src/main.rs
bin/domain/imag-timetrack/src/cont.rs
bin/domain/imag-timetrack/src/day.rs
bin/domain/imag-timetrack/src/list.rs
bin/domain/imag-timetrack/src/month.rs
bin/domain/imag-timetrack/src/stop.rs
bin/domain/imag-timetrack/src/week.rs
bin/domain/imag-timetrack/src/year.rs
lib/core/libimagstore/src/store.rs
lib/domain/libimagdiary/src/diary.rs
lib/domain/libimagdiary/src/error.rs
lib/domain/libimagdiary/src/iter.rs
lib/domain/libimagnotes/src/notestore.rs
lib/domain/libimagtimetrack/src/iter/get.rs
lib/domain/libimagtimetrack/src/iter/mod.rs
lib/domain/libimagtimetrack/src/timetrackingstore.rs
lib/domain/libimagtodo/src/iter.rs
lib/domain/libimagtodo/src/taskstore.rs
lib/entry/libimagentryannotation/src/annotation_fetcher.rs
lib/entry/libimagentrycategory/src/register.rs

Remove: Store::retrieve_for_module

---

Cargo.toml
bin/core/imag-git/Cargo.toml
bin/core/imag-git/src/main.rs
bin/core/imag-git/src/ui.rs
bin/core/imag/build.rs
imagrc.toml
scripts/release.sh

imag-git: init

---

bin/core/imag-view/Cargo.toml
bin/core/imag-view/src/main.rs
bin/core/imag-view/src/ui.rs
lib/entry/libimagentryview/Cargo.toml
lib/entry/libimagentryview/src/builtin/md.rs
lib/entry/libimagentryview/src/builtin/mod.rs
lib/entry/libimagentryview/src/error.rs
lib/entry/libimagentryview/src/lib.rs

imag-view: markdown compile

---

bin/core/imag-view/src/main.rs
bin/core/imag-view/src/ui.rs

imag-view argument to put seperator between shown entries

---

bin/domain/imag-contact/src/main.rs

Deny non-absolut import pathes

---

.travis.yml
lib/core/libimagerror/src/iter.rs
lib/core/libimagerror/src/str.rs
lib/core/libimagrt/src/configuration.rs
lib/core/libimagrt/src/runtime.rs
lib/core/libimagstore/src/configuration.rs
lib/core/libimagstore/src/file_abstraction/fs.rs
lib/core/libimagstore/src/file_abstraction/inmemory.rs
lib/core/libimagstore/src/file_abstraction/mod.rs
lib/core/libimagstore/src/store.rs
lib/core/libimagstore/src/storeid.rs
lib/core/libimagstore/src/util.rs
lib/domain/libimagtimetrack/src/iter/mod.rs
lib/entry/libimagentrycategory/src/register.rs
lib/entry/libimagentrydatetime/src/datetime.rs
lib/entry/libimagentrygps/src/entry.rs
lib/entry/libimagentrylink/src/external.rs
lib/entry/libimagentrylink/src/internal.rs
lib/entry/libimagentrymarkdown/src/processor.rs
lib/etc/libimagnotification/src/result_notification.rs
lib/etc/libimagtimeui/src/date.rs
lib/etc/libimagtimeui/src/datetime.rs
lib/etc/libimagtimeui/src/time.rs
lib/etc/libimagutil/src/cli_validators.rs
lib/etc/libimagutil/src/date.rs
lib/etc/libimagutil/src/key_value_split.rs
lib/etc/libimagutil/src/variants.rs

Add a travis job that applies clippy and add patches which fix the issues reported by clippy.

Travis: clippy

---

bin/domain/imag-contact/src/create.rs

Fix: Make most fields optional

---

bin/core/imag-gps/src/main.rs
lib/entry/libimagentrygps/src/types.rs

libimagentrygps: 32 bit gps values

---

lib/domain/libimagtodo/src/error.rs
lib/domain/libimagtodo/src/task.rs
lib/domain/libimagtodo/src/taskstore.rs

Refactor error handling, use more error chaining

---

lib/core/libimagstore/src/error.rs
lib/core/libimagstore/src/store.rs

Add more error contextual information in store errors.

Add information about which storeid is the cause of the error in errors

---

lib/core/libimagstore/src/store.rs

Before we had the problem that when iterating over _a lot_ (like 5k)
entries and also fetching them, at some point the OS would return with
"Too many files open".
That is because the store internally caches a lot.
With this change, the Store gets an API to query how big the cache is,
how much the cache can currently hold and (and that's the main thing in
this patch) to flush the cache to disk.
A function to simply ask the store whether its cache should be flushed
(which would us require to ask the OS how many files we can open...
which would be possible with `libc::getrlimit`) does not yet exist,
though, but could be added easily if desired.

Add functionality to flush the internal cache

---

bin/core/imag-diagnostics/Cargo.toml
bin/core/imag-diagnostics/src/main.rs
lib/core/libimagstore/src/store.rs

imag-diagnostics: flush cache

---

Cargo.toml
bin/core/imag-category/Cargo.toml
bin/core/imag-category/README.md
bin/core/imag-category/src/main.rs
bin/core/imag-category/src/ui.rs
doc/src/04020-module-category.md
lib/entry/libimagentrycategory/src/entry.rs
lib/entry/libimagentrycategory/src/store.rs
scripts/release.sh

imag-category: Initial import

---

doc/src/00000.md
doc/src/09020-changelog.md

Preparation branch for the 0.8.0 release - the last release before my departure.

Prepare for 0.8.0

---

lib/entry/libimagentrylink/src/external.rs

Fix comment for rustc 1.26

---

bin/domain/imag-log/src/main.rs

The problem was that the used `Diary::diary_names()` iterator does not
call `unique()` on its output.
That decision was made because the return type would get more
complicated with that feature.
Now that rustc 1.26 with Impl Trait is out, we can refactor the return
types of these functions (so also with `Diary::diary_names()`) to
automatically do this.
---
Closes #1487

Fix: Duplicated printing of entries with "show --all"

---

.travis.yml
bin/domain/imag-habit/src/main.rs

We're moving away from github, but as we're not moved yet, we keep using travis :smile:

Update rustc in travis

---

bin/core/imag-store/src/verify.rs
lib/core/libimagstore/src/store.rs
lib/core/libimagstore/src/util.rs

libimagstore: fix use backend

---

bin/domain/imag-diary/src/create.rs
lib/domain/libimagdiary/src/diary.rs

Imag diary/fix missing header

---

lib/core/libimagstore/src/file_abstraction/fs.rs

This patch changes the filesystem-backend implementation of libimagstore
to open files on each read/write rather than holding the file handle in
memory at all times.
Whenever a lot of imag store entries are read into memory, the imag
process may ran out of file descriptors. With this patch applied, a
`Store::get()` call on an entry which is not yet in the store cache
would cause the file to be read, but the FD being dropped after that.
Likewise, a `Store::update()` (which is also called if the imag entry is
dropped) would re-open the file on the filesystem and write the contents
from the imag store cache back to the file.
With this patch, opening hundrets or thousands of imag entries should be
no problem anymore, only the available memory should be a limit then.
Signed-off-by: Matthias …

Optimize backend impl to not hold open files

---

.travis.yml

Update rust compiler versions
