matthiasbeyer/imag

src/module/bm/mod.rs

Adds missing filter functionality for BM subcommand `list`.

BM::command_list() add filter functionality

---

src/main.rs
src/runtime.rs

The logger instance cannot be configured through the configuration file, as this is kinda bulky to use and we can log to debug much earlier now.

ImagLogger can be configured through the CLI only now

---

src/configuration.rs
src/runtime.rs

Refactoring of the internal representation of the configuration file.
Also removes the possibility to set verbosity and debugging flag in the config file, as I consider this bad anyways and it allows us now to setup the logger earlier in the startup phase, which means more code which can use debugging output.

Config refactor

---

src/module/helpers/header/tags.rs

We did not check whether we got the TAGS array in here.

Fix: [warn]: Malformed Header, expected Array

---

src/module/notes/mod.rs

Include the tags in the browser view on `imag notes open`.
Some refactoring included.

Notes open include tags

---

src/main.rs
src/module/bm/mod.rs
src/module/helpers/cli.rs
src/module/helpers/content.rs
src/module/helpers/header/mod.rs
src/module/helpers/header/tags.rs
src/module/helpers/utils.rs
src/module/notes/mod.rs
src/storage/file/hash.rs
src/storage/file/id.rs
src/storage/file/id_type.rs
src/storage/file/mod.rs
src/storage/json/parser.rs
src/storage/mod.rs
src/storage/parser.rs
src/ui/external/editor.rs

Finally, I cleaned up a bit.
The `dead_code` warning is still disabled, though I might enable it anytime soon.

Turn warning into hard errors and fix them

---

etc/cli.yml
src/module/notes/mod.rs

Add subcommand for `notes`: `show`, to print notes on the commandline, unrendered.

Notes show

---

src/module/notes/mod.rs

Was still there because of the merge order.

Remove parser variable from Notes::command_show()

---

doc/default.nix

Alters the `default.nix` in the `doc/` folder to list the (latex-)dependencies for building the paper explicitly, rather than listing some random collections which may or may not contain the required packages.
Just relevant for nix(os) users. Anyways helpful for others, as they know which latex packages to install for building the doc.

doc/default.nix: List dependencies for building the paper explicitely

---

.travis.yml

Optimize the CI-time for `./doc` changes by not doing anything if there are only changes in `./doc`.
@TheNeikos careful review would be appreciated!

travis: exit(0) if there are only changes in ./doc

---

.travis.yml

Test sub-crates if there are changes in them, as pointed out by @TheNeikos in #99, this wasn't happening before.

travis: Run cargo chain for all cargo files

---

libimagstore/src/store.rs

These methods were intended for managing cached entries. Sice it was
decided not to serve caching in the store, these methods are no longer
needed.

Remove methods which are not needed anymore

---

libimagrt/src/lib.rs

Make the `runtime` module of `libimagrt` public, so we can use the `Runtime` type.

rt: Make runtime module public

---

libimagstore/src/header.rs

Closes #127 
I will not merge this yet, as we have to build the default-header. I will implement it as far as the docs say by now, but maybe we want more...

Dont pass the table to the header object, but generate it in ::new()

---

libimagstore/src/store.rs

Add missing `pub` keywords on a few `Entry` functions.

Fix: Add missing "pub" on Entry functions

---

libimagstore/src/store.rs

We don't want to panick if a lock inside the store is broken. We want to
notify the user, so she can start panicking.

Add missing error handling

---

libimagstore/src/storeid.rs

Fixes private `IntoStoreId` trait which should be public.

Fix: Make IntoStoreId public

---

libimagrt/src/configuration.rs
libimagrt/src/error.rs
libimagrt/src/runtime.rs
libimagstore/src/error.rs
libimagstore/src/store.rs

Removes unused imports.
We really should enable the appropriate checks for this. @TheNeikos feel free to submit a PR for denying unused imports.

Remove unused imports

---

libimagutil/Cargo.toml
libimagutil/src/lib.rs
libimagutil/src/trace.rs

This is an utility for printing a trace of errors.
Could be rather useful for binary implementations, so we can tell the user what went wrong.

Add error tracing utility

---

libimagrt/src/runtime.rs

rt: Remove short versions for "config" and "runtimepath" std arg

---

doc/src/05000-lib-module.md

Remove the chapter on "libimagmodule" from the documentation. "libimagmodule" was removed.

doc: Remove file for "libimagmodule", as this was removed

---

libimagutil/Cargo.toml

Updates the `regex` crate dependency of `libimagutil` to `0.1.54`.

util: Update regex = 0.1.54

---

libimagstore/src/store.rs

Add function to get the inner toml object from an `EntryHeader`.
Ready for review here.

EntryHeader: Function to get toml object

---

libimagrt/Cargo.toml
libimagrt/src/configuration.rs
libimagrt/src/lib.rs
libimagrt/src/runtime.rs

Required for #225, as with TOML everything gets simpler everywhere and especially in the store library.
This also solves some dependency issues with the `config` crate (which depends on `nom ~1.0.0` behind the scenes and this leads to incompatible versions in some places).
@TheNeikos and @neithernut please review ASAP!

Switch configuration language to TOML

---

libimagutil/src/ismatch.rs
libimagutil/src/lib.rs

@TheNeikos proves you wrong.
This adds a `is_match!()` macro, to condense this:
```rust
if match x { FooBar(_) => { true }, _ => { false } } {
// ...
}
// or even
if foo.all(|x| match x { Some(FooBar(_)) => { true }, _ => false }) {
// ...
}
```
down to
```rust
if is_match!(x, FooBar(_))
// ...
}
// or 
if foo.all(|x| is_match!(x, Some(FooBar(_)))) {
// ...
}
```

Add ismatch!() macro

---

libimagstore/Cargo.toml

Update the `glob` dependency from `0.2.10` to `0.2.11`, which brings us some bug-fixes and implements `Error` on `PatternError`, which will help us in some other PRs with smaller issues.
---
Closes #234

libimagstore: Update glob 0.2.10 -> 0.2.11

---

imag-counter/src/main.rs
imag-link/src/main.rs
imag-store/src/main.rs
imag-tag/src/main.rs
imag-view/src/main.rs
libimagrt/src/runtime.rs

Closes #280 
The code which was run _before_ the logger init was getting too complex. We need logging there. Therefor I'm changing this to happen implicitely on runtime setup.

Move logger initialization to earliest possible point

---

libimagnotes/src/note.rs

We might want to `Deref` a `Note` to get the underlying `FileLockEntry`.
(This was extracted from another PR I'm working on)

impl Deref for Note

---

libimagrt/src/runtime.rs

Removed the logger initialization, which was not caught by review
somehow.
This patch re-adds the appropriate lines.

Partially revert 7f1a671

---

libimagrt/src/edit.rs

We missed that in the initial PR.

Implement Edit for String

---

imag-link/src/main.rs

The `imag-link` binary had an issue with the CLI parsing as there was an layer of unpacking CLI values missing.
This commit fixes this.

Bugfix: Add missing level of unpacking in cli helpers

---

libimagrt/src/configuration.rs
libimagrt/src/runtime.rs

Rename method to be consistent with other crates.

Rename: kind() to err_type()

---

libimagentrylist/src/listers/path.rs
libimagstore/src/store.rs
libimagstore/src/storeid.rs

but make it a new type instead.
Also derive and implement as many traits as possible for it, so we keep
backwards compatibility as much as possible.
Anyways, we need to rewrite some code for this.
Suggested-by: Marcel Müller <neikos@neikos.email>
Signed-off-by: Matthias Beyer <mail@beyermatthias.de>
---
@TheNeikos can you come up with code which keeps backwards compatibility to 100%? I don't think so, feel free to surprise me!
---
For the curious: This refactoring would enable us to implement traits on the type elsewhere which would allow us to greatly improve the overall codebase.
It also gives us the possibility to implement functions on the type which then can be used to check certain invariants, for example that the `StoreId` should always be an absolute path but starting from the …

Remove typedef for StoreId type

---

libimagstore/src/configuration.rs

These keys are not used, actually.

Remove old check from config validation

---

libimagentrylink/src/external.rs

We could really use this helper function in other modules.

Rename and make public: is_link_store_id() -> is_external_link_storeid()

---

libimagerror/src/error_gen.rs
libimagstore/src/hook/error.rs

I totally missed that this is also possible here.

libimagerror: Impl Into<error name> for all <errorkindname>

---

libimagnotes/src/note.rs

This is what keeps #209 from building on `rustc 1.10`.

Remove unused import

---

libimagentrylink/src/internal.rs

Use `IntoError` functionality to have less noise in the error construction code.

Use IntoError to have less noise in the error construction code

---

libimagstore/src/store.rs

This fixes the `glob()` pattern argument for `Store::retrieve_for_module()`, which was buggy.

Fix glob() pattern

---

libimagstore/src/store.rs

Closes #405 
@TheNeikos Please review this and whether I'm doing serious bullshit here or whether this is a good idea actually.

Remove duplicated StoreId member in FileLockEntry, use member from Entry

---

Makefile
README.md

One can now type:
```
$> make
```
Which builds all the modules and places them in a `out/` directory of the project root for easy
finding.
Alternatively one can type:
```
$> make $module
```
Where `$module` is one of the `imag-*` names, such as `counter`, `imag-link`, etc.
To clean up the `out/` directory it's `$> make clean`
-----
The `make clean` could also run `cargo clean` if needbe, but I wasn't sure if that would be desirable or not.

Adds a Makefile for building modules

---

libimagstore/src/error.rs
libimagstore/src/store.rs

This PR adds some error types which will be used by the Store functions so one can clearly see which store function caused the error.
Basically this adds another level in the error trace, just to be a bit more verbose about the path the error took.

Add a set of error kinds to identify the store call the error came from

---

libimagrt/src/edit.rs

Fix: Re-writing content of String in edit_in_tmpfile()

---

CONTRIBUTING.md

I'm not sure here: We do not have a license-header in the files itself, but a license file which lives in the repository.
We might have to fix this.
@neithernut , @TheNeikos and maybe @llogiq ... what do you think on the subject of having a license statement in all files - is it necessary?

Add Developers Certificate of Origin

---

imag-diary/src/list.rs
libimagentrylist/src/listers/core.rs

Make CoreLister generic, so we can pass functions _and_ closures into it.

libimagentrylist: Make CoreLister generic

---

libimagref/src/reference.rs

We cannot offer the former because deleting self would always fail as
the FileLockEntry is already borrowed from the store, so the store
declines this.
But deleting by hash works.

Fix: We cannot offer a Ref::delete(self), but a Ref::delete_by_hash()

---

libimagstore/src/store.rs

As the Aspect execution catches the aborting hooks and returns them, we
cannot have a non-aborting error here, so there is no point in checking
for aborting errors.
Closes #465

Remove checking for aborting errors

---

libimagentrylist/Cargo.toml
libimagentrylist/src/lib.rs
libimagentrylist/src/listers/line.rs
libimagentrylist/src/listers/path.rs
libimagstore/src/hook/aspect.rs
libimagstore/src/store.rs
libimagutil/src/iter.rs
libimagutil/src/lib.rs

Add a utility that folds an iterator into a result and uses it to reduce
boilerplate in the codebase.

Add a `fold_ok` utility.

---

libimagstore/src/hook/aspect.rs

Use `Result::or_else` instead of matching and no-oping the `Ok` case
manually and extract a helper to centralize repeated trace logic.

Cleanup `HookError` tracing logic.

---

imag-bookmark/src/main.rs
imag-counter/src/create.rs
imag-counter/src/delete.rs
imag-counter/src/interactive.rs
imag-counter/src/main.rs
imag-diary/src/delete.rs
imag-diary/src/view.rs
imag-link/src/main.rs
imag-notes/src/main.rs
imag-store/src/create.rs
imag-store/src/delete.rs
imag-store/src/get.rs
imag-store/src/retrieve.rs
imag-store/src/update.rs
imag-tag/src/main.rs
imag-view/src/main.rs
libimagerror/src/trace.rs

Could be nice to write some binaries where we often use this, actually.
Some commits will follow where I clean up things.

Add utility for calling trace_error() and exit()

---

bin/src/main.rs

Previously, flags like `--version` were ignored, and would always display the help. This fixes that and also adds in the ability to write `imag --debug foo`.

Fix flags for root command not working; Added in debug forwarding

---

bin/src/main.rs

With this patch, we list "imag counter" instead of "imag-counter" in the
help output.

Remove dash from command listing

---

imag-view/src/main.rs

imag-view: Use get() instead of retrieve()

---

imag-notes/src/ui.rs

Surprisingly, the ArgGroup feature of clap (which was applied in a wrong
way here anyways) caused the "name" Arg to be inaccessible. I don't know
why, but that's it.
Removing the group fixes the issue.
---
Closes #461

Fix panic on unwrap()

---

libimagentrymarkdown/src/lib.rs

Number 2 in a series of seven branches addressing #507.

libimagentrymarkdown: Deny warnings

---

libimagentryselect/src/lib.rs

Number 3 in a series of seven branches addressing #507.

libimagentryselect: Deny warnings

---

.imag-documentation/Cargo.toml
.imag-documentation/src/lib.rs
Makefile

Adds a meta-crate (hidden in a dot-directory) which depends on all `libimag*` crates, so we can build the complete library documentation from a single crate.
Closes #472

Imag (library) documentation

---

libimagerror/src/error_gen.rs
libimagerror/src/lib.rs

Number 4 in a series of seven branches addressing #507.

libimagerror: Deny warnings

---

.travis.yml

As we now have a IRC channel registered with freenode, we could use the travis IRC bot to notify on builds! :smile:

Add travis setup for IRC notifications

---

.travis.yml

As said in https://github.com/matthiasbeyer/imag/pull/650 all we can do is wait - not really. We can also allow travis beta to fail.
This PR adds a patch that allows the travis job with the beta compiler to fail and _this patch should be reverted as soon as possible_.
But with this patch applied we can continue working on imag.

Allow travis to fail beta, temporarily

---

.travis.yml

This reverts commit f353d08cd1296d5cee71dbd784b0abf8923d90c9.
---
Closes #652 
Blocked until succeeding on travis.

Revert "Allow travis to fail beta, temporarily"

---

.travis.yml

Because they fail anyways... and I do not really care for nightly for imag, so we can disable it.

Disable nightly builds on travis

---

libimagutil/src/debug_result.rs
libimagutil/src/info_result.rs
libimagutil/src/log_result.rs
libimagutil/src/warn_result.rs

Some cleanup patches for the `Result` extensions in `libimagutil`.
(Only comments, actually...)

Libimagutil/result extension cleanup (documentation)

---

libimagutil/src/lib.rs
libimagutil/src/warn_exit.rs

Can be helpful in some `imag-*` implementations.

libimagutil: Add warn_exit() convenience helper

---

imag-store/tests/002-retrieve_test.sh

We missed them in #667 - why didn't the test suite fail.
@mario-kr I'd like you to investigate. Go to master (and, if this is already merged by then, revert this patch) and find out why the test suite did not fail.
And, of course, provide patches to fix the testing-suite.

Fix absolute StoreId specification in imag-store test

---

libimagstore/src/store.rs

The lastest release of the `toml-rs` crate (2.1) removes leading spaces
before arrays and tables, causing our tests to fail.
This fixes it.
---
Related: https://github.com/alexcrichton/toml-rs/issues/113

Add newline before header

---

libimagstorestdhook/src/vcs/git/update.rs

Closes #755 
This _seems_ to fix the issue from #755, though I'm not completely sure whether this is the actual fix. For now it seems to work.

libimagstorestdhook/git: fix empty commits

---

libimagstore/src/file_abstraction.rs
libimagstore/src/store.rs

WIP PR on #698 
@TheNeikos do you see the error here? The tests panic [on line 2244](https://github.com/matthiasbeyer/imag/blob/libimagstore/store-tests-extend-create-delete-get-test/libimagstore/src/store.rs#L2244) which indicates that the `Store::delete()` operation reports a false positive and the entries are not removed from the internal hashmap.
(See also the fix for the `Store::get` function I introduced to confirm my above statement is right).

libimagstore/store-tests: extend create delete get test

---

Makefile

I noticed that the `imag-bin`-targets werent really included when running for example `make all`.
Beside that, I added a ` | sort` behind the `find`, so the build order should mostly be the same (looks nicer to me).
Additionally, I fixed the `imag-bin-release` target, which simply couldnt work that way.

Fix include bin target in other targets

---

libimagstore/src/store.rs

Erroring-Hook-tests for `libimagstore`.
Not ready yet and should also be rebased after #761 is merged.

libimagstore/store-tests: erroring hooks

---

imag-bookmark/src/main.rs
imag-ref/src/main.rs
libimagref/src/lister.rs
libimagref/src/reference.rs

Some small cleanup patches for various crates, so they do not pollute the travis output anymore.
Also enforce warnings = errors.

Warning cleanup

---

libimagstore/src/file_abstraction.rs
libimagstore/src/store.rs

PR on #698 
---
What I debugged so far:
Randomly tests fail. On the latest commit it _seems_ to be the `Store::move_by_id()` that returns an `FileNotFound` error whenever it has to return an `Ok(())` in the failing tests.
What I guess:
1. The tests run all on the same internal HashMap
1. The tests run all with the same store-id / file names
1. One test (one thread) moves the "test" storeid away and succeeds
1. Another test (thread) tries to move the "test" storeid and does not find it, because it is already moved.
If this is the error, the obvious fix would be to name all StoreIds used in tests uniquely.
I will try this now and then start my test script (`while [[ true ]]; do RUST_BACKTRACE=1 cargo test -j 16 || break; done`) on my private testing machine.

libimagstore/store-tests: fix poisonerror panic

---

default.nix

Add dep for pure nix build: which

---

libimagentrylink/Cargo.toml
libimagentrylink/src/internal.rs
libimagentrylink/src/lib.rs

Contains two bug fixes for rather critical things.
Should go into 0.2.0, as these bugs are (IMHO) really serious and completely break the linking feature.
Awesome we can test such things now!

libimagentrylink: tests

---

libimagstorestdhook/src/denylinkeddelete.rs
libimagstorestdhook/src/lib.rs

This adds a hook which denies `Store::delete()` if there are still links in the entry.

libimagstorestdhook: deny delete of linked entries

---

libimagstore/src/store.rs

The name of the storeid was duplicated, which caused the tests to fail
from time to time.
This patch fixes the name of the entry which is used to test.

Fix test StoreId name

---

imag-bookmark/src/main.rs
imag-link/src/main.rs
libimagbookmark/src/collection.rs
libimagentrylink/src/external.rs

Welcome to the first iteration (pun intended) on `Matzes Fun with Iterators`.
Today, we talk about filter iterators.
Filter iterators are a funny thing. For example, see this wonderful pull request, containing a load of different filter iterators, all based on one simple iterator containing some boolean logic at its very core.
This pull request is not ready yet, though. It will get some more commits and will utlimately contain a rewrite of the interface for the external linking traits, so they return iterators instead of vectors. How is that? Yeah, we like that; it is great!
That's it for todays episode on `Matzes Fun with Iterators - Filter iterators`. See how easily we had fun?

libimagentrylink: external linking iterator interface

---

libimagerror/src/iter.rs
libimagerror/src/lib.rs

Adds a new trait `libimagerror::iter::TraceIterator` that provides the methods as described in #813.

Add Iterator for Iterator<Item = Result<T, Error>> tracing

---

Makefile

Adds a new makefile target for `cargo check`ing all the crates.

Make: Add -check targets to "cargo check"

---

libimagutil/src/edit.rs

`Write` is implemented on both `&NamedTemporaryFile` and `&File` so you don't actually need a mutable reference. I wish there were a better way to do this but such is life.

Don't re-open temporary file.

---

bin/Cargo.toml
bin/build.rs

I present a solution for the "shell-completion problem", though the "how" may be a bit... discussable.
It somehow works, which is kind of surprising, as it literally is my first macro in rust.
There definitely is space for improval, as there is still duplicate code (9 times `.subcommand(...)`).
Testing is definitely welcome, as this work is in the "10 minutes ago I ran it and it actually worked (on my machine)" kind of state.
Also this kind of solution will require maintenance when adding new binaries to imag. Furthermore, the completion is generated at compiletime, which might or might not be considered a downside.

Add shell completion

---

imag-bookmark/Cargo.toml
imag-counter/Cargo.toml
imag-link/Cargo.toml
imag-notes/Cargo.toml
imag-ref/Cargo.toml
imag-todo/Cargo.toml
libimagentryfilter/Cargo.toml
libimaginteraction/Cargo.toml
libimagrt/Cargo.toml
libimagrt/src/runtime.rs
libimagtimeui/Cargo.toml

Therefor we need to have at least clap 2.16.1.
We bake this into libimagrt::runtime::Runtime, so all binary crates
should automatically have it.
---
Closes #495
Or does it? We then have shell compl for `imag-foo` but not yet for `imag` itself. At least a step into the right direction, IMHO.

Bake in shell-compl generation

---

imag-store/Cargo.toml
imag-view/Cargo.toml
libimagentrytag/Cargo.toml

Bump `clap` to at least 2.17 in crates where it isn't already.

Clap version bump

---

Makefile

As implemented in https://github.com/kbknapp/cargo-outdated/issues/29 we can now pass `--manifest-path` and `--lockfile-path` to call `cargo-outdated` by a script.
I tested this and I will merge as soon as CI finishes.

Add support for cargo-outdated 0.3.0

---

imag-link/src/ui.rs

Closes a bug reported in https://github.com/matthiasbeyer/imag/issues/768#issuecomment-264851895
Note that we still need to specify the full URL here.

Fix: We need an argument here

---

libimagrt/src/lib.rs
libimagrt/src/logger.rs

This commit makes the logging functionality types from libimagrt public,
so the libimagruby implementation can re-use the ImagLogger type.
---
Extracted from #847 - @mario-kr I guess this is okay, isn't it? I'm not sure. We expose the logging utilities of libimagrt - still, Rust binaries should initialize the logger via the `Runtime` type.
This is just done so I can use the `ImagLogger` type in the Ruby library to initialize a logger from Ruby code.

Make logger types public

---

libimagrt/src/logger.rs

Extracted from #847 
This patch adds a functionality to the `ImagLogger` to _not_ print filepath and line number in debug logging.
Yes, this is even more overhead for the logger - but I really do not care at this point as we really need this in the Ruby library - because logging from Ruby would yield the very same line for each Ruby logging call, because the acutal `debug!()` call is done in Rust code, not in Ruby code...

ImagLogger: Add option to not include file/line in dbg logging

---

bin/build.rs

There was a breaking change in cargo which is fixed by this commit
Affected: beta builds (as of writing of this commit).

Fix build-script of imag-bin

---

libimagruby/src/entry.rs

Fixes a macro which didn't pass the error type expression further down...

Fix: Pass error return expression further down

---

imag-store/Cargo.toml
imag-store/src/create.rs
imag-store/src/retrieve.rs
imag-store/src/util.rs
libimagentryfilter/src/builtin/header/field_exists.rs
libimagentryfilter/src/builtin/header/field_isempty.rs
libimagentryfilter/src/builtin/header/field_predicate.rs
libimagentryfilter/src/builtin/header/version/eq.rs
libimagentryfilter/src/builtin/header/version/gt.rs
libimagentryfilter/src/builtin/header/version/lt.rs
libimagentrylink/src/external.rs
libimagentrylink/src/internal.rs
libimagentrytag/src/tagable.rs
libimagentryview/src/builtin/plain.rs
libimagentryview/src/builtin/stdout.rs
libimagnotes/src/note.rs
libimagref/src/reference.rs
libimagruby/src/entry.rs
libimagstore/Cargo.toml
libimagstore/src/lib.rs
libimagstore/src/store.rs
libimagstore/src/toml_ext.rs
libimagstore/src/util.rs

Followup for #835 
This eliminates the `EntryHeader` type by moving the functionality to traits implemented on `toml::Value`.
Refactoring is about to be done.

libimagstore: Eliminate EntryHeader type

---

libimagentrylist/Cargo.toml

Small bump.
We don't need to force the newest version (2.20.5 as of writing), as cargo does this for us, so I won't bump the version here.

Make clap version more specific

---

Makefile
README.md

With the introduction of workspaces, some things became sort-of wrong in the Makefile. E.g. running `make clean` would clean `$IMAG/target` as many times as crates are specified in the the `members` section in `$IMAG/Cargo.toml`.
AFAIK, the same applies to `cargo outdated` and `cargo update`.
Please review/test to make sure I'm not wrong 😄

Makefile use workspaces

---

.travis.yml

I guess travis does not send irc notifications anymore because the indentation is wrong here... I don't know for sure, though.

travis: IRC notifications fixes

---

libimagentrylink/src/internal.rs

Broken via merging. :curly_loop:

Fix: Link::exists() must return Result<bool> now

---

bin/build.rs
libimagutil/src/cli_validators.rs
libimagutil/src/iter.rs

We had quite some files where we had no license header I noticed. This fixes it.

Add missing license headers

---

libimagentrytag/src/tag.rs

Small enhancement for the clap validator in `libimagentrytag`, so we can use it outside of the clap space as well.

Add is_tag_str(&str) wrapper for is_tag(String)

---

libimagstore/src/lib.rs

This makes the `file_abstraction` module pub.
We need this to be able to use the in-memory backend when using the store in tests.
As this module itself only exports the required parts, we can export the whole module instead of reexporting its types in `libimagstore::store` or whatever.
Relevant for @irobert91 as well!

Make libimagstore::file_abstraction pub

---

libimagrt/Cargo.toml
libimagrt/src/configuration.rs
libimagrt/src/lib.rs
libimagrt/src/runtime.rs

Some cleanup in the `libimagrt` codebase.
I'll wait for #947 before merging this.

libimagrt: cleanup

---

imag-store/src/dump.rs
imag-store/src/main.rs
imag-store/src/ui.rs

This uses the new backend-replacing mechanism to dump the store to stdout.
It does currently not work as expected.
To reproduce:
```bash
../target/debug/imag-store --config ../imagrc.toml --override-config store.implicit-create=true --rtp /tmp/ dump
```
Outputs:
```
Config file parser error:
ERROR[   1]: a custom error
[imag][WARN]: No config file found.
[imag][WARN]: Continuing without configuration file
ERROR[   1]: StoreId 'id' part is absolute (starts with '/') which is not allowed
ERROR[   1]: StoreId 'id' part is absolute (starts with '/') which is not allowed
{"version":"0.3.0","store":{}}
ERROR[   1]: JSON error
ERROR[   2]: IO Error -- caused:
ERROR[   3]: Could not instantiate
[imag][ERROR]: Loading Store IO backend failed
```
So the store gets actually dumped to stdout as …

Imag store dump

---

libimagstore/src/file_abstraction/fs.rs

This fixes a nasty bug when removing content from files, where remaining things were in the file after writing to it.

Fix: Re-set file length before writing to it

---

imag-link/src/main.rs
imag-link/src/ui.rs

Closes #964 
The link-consistency-check does report "OK" even when the links are inconsistent.
Filed in #990

Export store-consistency-check from libimagentrylink in UI

---

.travis.yml

As the dependency
unicode-bidi
requires rustc 1.17 as minimum version of the rust compiler, we have to
update as well.

Update to rustc 1.17

---

imag-link/Cargo.toml
imag-link/src/main.rs
libimagutil/Cargo.toml
libimagutil/src/lib.rs
libimagutil/src/testing.rs

:tada: This is Issue/Pr no. 1000. Holy cow! :tada: 
This moves the testing functionality for CLI testing to the libimagutil (behind a feature gate, of course).

Move utility functionality for tests into libimagutil

---

lib/core/libimagerror/src/lib.rs
lib/core/libimagstore/src/lib.rs
lib/domain/libimagbookmark/src/lib.rs
lib/domain/libimagcounter/src/lib.rs
lib/domain/libimagmail/src/lib.rs
lib/domain/libimagmail/src/mail.rs
lib/domain/libimagtimetrack/src/iter/filter.rs
lib/domain/libimagtimetrack/src/iter/mod.rs
lib/domain/libimagtimetrack/src/lib.rs
lib/domain/libimagtodo/src/error.rs
lib/domain/libimagtodo/src/lib.rs
lib/domain/libimagtodo/src/task.rs
lib/entry/libimagentryannotation/src/lib.rs
lib/entry/libimagentrycategory/src/lib.rs
lib/entry/libimagentrydatetime/Cargo.toml
lib/entry/libimagentrydatetime/src/lib.rs
lib/entry/libimagentryedit/src/lib.rs
lib/entry/libimagentryfilter/src/lib.rs
lib/entry/libimagentrylink/src/lib.rs
lib/entry/libimagentrymarkdown/src/lib.rs
lib/entry/libimagentryref/src/lib.rs
lib/entry/libimagentrytag/src/lib.rs
lib/etc/libimaginteraction/src/lib.rs
lib/etc/libimagtimeui/src/lib.rs
lib/etc/libimagutil/src/lib.rs

This might get a bit lengthy. In this first patch, we deny all warnings, hopefully getting to a point where a whole imag build can be done with not one warning.
Patches for fixing the (now) compile errors will follow, feel free to contribute!

Fix warnings by not allowing them anymore

---

bin/core/imag-ref/src/main.rs
bin/domain/imag-mail/src/main.rs
lib/domain/libimagmail/src/iter.rs
lib/domain/libimagmail/src/mail.rs
lib/entry/libimagentryref/Cargo.toml
lib/entry/libimagentryref/src/hashers/nbytes.rs
lib/entry/libimagentryref/src/lib.rs
lib/entry/libimagentryref/src/lister.rs
lib/entry/libimagentryref/src/reference.rs
lib/entry/libimagentryref/src/refstore.rs
lib/entry/libimagentryref/src/util.rs

First crate tackled with this patchset, to move from wrapping an entry in `libimagentryref` to extending it via trait.
Only `libimagentryref` touched so far, no "user code" fixed.

libimagentryref: Extensions as Traits

---

bin/core/imag-tag/Cargo.toml
lib/core/libimagrt/Cargo.toml
lib/core/libimagrt/src/runtime.rs
lib/etc/libimagutil/src/testing.rs

This is necessary to be able to re-build a Runtime object with an new
set of "commandline arguments". For example if a test wants to test two
calls to imag, for example a "add" operation followed by a "remove" operation.
These functions are feature-gated therefor and should only be used in
tests.

Add store extraction to Runtime

---

bin/domain/imag-todo/Cargo.toml
bin/domain/imag-todo/src/main.rs
lib/domain/libimagtodo/src/error.rs
lib/domain/libimagtodo/src/lib.rs
lib/domain/libimagtodo/src/task.rs
lib/domain/libimagtodo/src/taskstore.rs

Not really sure if this is what you wanted... but here it is.
Instead of a `Task` type which wrapped a `FileLockEntry`, it's a `Task` trait implemented for FLE.
The naming scheme has become rather verbose.
Nothing is tested, but it builds.

imag-todo/libimagtodo: All extensions as traits

---

lib/entry/libimagentrydatetime/src/datetime.rs
lib/entry/libimagentrygps/src/entry.rs
lib/entry/libimagentrylink/src/internal.rs

This was able to slip because we did not use `Store::update()` at all, but relied on the `drop()` implementation which calls `Store::_update()`.
It was not that critical, as the tests simply did never hit the FS because of permission denied to create entries at `/`, but it wasn't nice either.

Fix Store loading in tests: Use in-memory store backend

---

lib/core/libimagstore/src/file_abstraction/fs.rs
lib/core/libimagstore/src/file_abstraction/inmemory.rs
lib/core/libimagstore/src/file_abstraction/iter.rs
lib/core/libimagstore/src/file_abstraction/mod.rs
lib/core/libimagstore/src/file_abstraction/stdio/mod.rs
lib/core/libimagstore/src/file_abstraction/stdio/out.rs
lib/core/libimagstore/src/store.rs

As we rely on the filesystem in Store::entries(), which is a bug and
shouldn't be done, we rewrite this function and use the file_abstraction
framework.
Closes #1055 
---
As a sidenote: The implementation is not optimal, though considered good enough right now.

Rewrite Store::entries() implementation

---

bin/core/imag-link/src/main.rs
doc/src/09020-changelog.md
lib/entry/libimagentrylink/src/external.rs
lib/entry/libimagentrylink/src/internal.rs

The `libimagentrylink` used header fields in the `imag` table, which is reseved for the `libimagstore`. This patch changes the location to `links`.
---
Also change that the implementation uses toml_query::set instead of
toml_query::insert.
Inserting values creates intermediate tables, set doesn't. And we really
want that convenience here, as the code is complex enough on its own.

libimagentrylink: Fix header locations

---

bin/domain/imag-diary/Cargo.toml
bin/domain/imag-diary/src/create.rs
bin/domain/imag-diary/src/main.rs
bin/domain/imag-diary/src/util.rs
doc/src/09020-changelog.md
imagrc.toml

The config file can be used to set a diary to create timed or non-timed entries.
Compiles and tested. But I would like to test it a bit more before merging, especially whether cli-overrides-config works.

imag-diary: per diary timed config

---

bin/domain/imag-timetrack/src/track.rs
doc/src/09020-changelog.md

It understands "now" from this point and can parse dates or date-times
(whereas dates get normalized to date + hour 0, minute 0, second 0).

Fix: Let the track command parse the start/end time more intelligently

---

Cargo.toml
bin/core/imag-grep/Cargo.toml
bin/core/imag-grep/src/main.rs
bin/core/imag-grep/src/ui.rs
doc/src/09020-changelog.md

A fairly simple crate, but nonetheless nice.
This crate could be a very good example on how to write imag commands, as a lot of features of the imag codebase are shown, such as iterator chaining, error handling and such.

imag-grep: Add new crate

---

lib/entry/libimagentrylink/Cargo.toml
lib/entry/libimagentrylink/src/external.rs

Fixes a bug where the query string in the toml query was faulty

libimagentrylink: test external linking

---

bin/core/imag-link/src/main.rs
bin/core/imag-tag/src/main.rs
lib/etc/libimagutil/src/testing.rs

We should not rely on a string which looks like a default entry, but simply create an empty entry and parse it to a string.

Testing default entry fix

---

lib/core/libimagrt/src/logger.rs

Before, handlebars automatically applied html escaping, which resulted
in <>'& beeing escaped. But we don't need to escape for terminal output.
---
Closes #1095

Register the no-escape escape functionality in handlebars

---

doc/src/09020-changelog.md
lib/core/libimagstore/src/store.rs

This patch fixes a problem where the Store::delete() function only
checked the store-internal cache whether an entry exists, but not the
Filesystem. After this patch is applied, the Store::delete() function
also checks the filesystem whether the entry exists.
---
Closes #1067

Fix: Store::delete() should check FS as well

---

lib/entry/libimagentrygps/src/entry.rs
lib/entry/libimagentrygps/src/types.rs

Required by the `imag-gps` plumbing command.

libimagentrygps: More functionality

---

bin/core/imag/Cargo.toml
doc/src/00000.md
doc/src/09020-changelog.md
lib/entry/libimagentrygps/Cargo.toml

Resubmitted https://github.com/matthiasbeyer/imag/pull/1112
This branch contains the release already.

v0.4.0 branch

---

doc/src/09020-changelog.md
lib/core/libimagrt/src/logger.rs

The logger was not able to handle multiple destinations before. Now it
is possible for the logger.
The file must be held behind an Arc<Mutex<_>> so we can use the logging
from multiple threads but also because we need to borrow mutably, so
that bit changes whith this commit.

Add multi-destination logging to logger

---

lib/core/libimagrt/Cargo.toml
lib/core/libimagrt/src/lib.rs
lib/core/libimagrt/src/logger.rs
lib/etc/libimaginteraction/Cargo.toml
lib/etc/libimaginteraction/src/format.rs
lib/etc/libimaginteraction/src/lib.rs

I moved this code because we need handlebars in various places, I would say. Hence having a library which contains all our helpers would be neat, IMO.
I actually need helpers in the `imag-contact` implementation, so this blocks the implementation of `imag-contact` in a certain way.

Move handlebars custom helpers to libimaginteraction

---

.travis.yml

We want to be able to compile imag with the latest compiler, but also
two compilers before the current one.
So Update the travis spec to include rustc 1.19 and 1.20, but not 1.17
and 1.18 anymore.

travis: rustc 1.17/1.18 -> 1.19/1.20

---

imagrc.toml

Explain how the module logging destinations work, remove the specified
logging destination, because the global log definition already logs to
stderr.
libimagstore logs with trace now, also to a logfile in /tmp/

Alter default configuration

---

doc/src/09020-changelog.md
lib/core/libimagstore/src/file_abstraction/fs.rs
lib/core/libimagstore/src/file_abstraction/inmemory.rs
lib/core/libimagstore/src/file_abstraction/mod.rs
lib/core/libimagstore/src/file_abstraction/stdio/mod.rs
lib/core/libimagstore/src/file_abstraction/stdio/out.rs
lib/core/libimagstore/src/store.rs

Before the iterator did also yield storeids for directories, which was a
bug.

Fix Store::entries() to not yield directories

---

bin/core/imag-view/src/main.rs
bin/core/imag/src/main.rs
bin/domain/imag-bookmark/src/main.rs
bin/domain/imag-diary/src/util.rs
doc/src/09020-changelog.md
lib/core/libimagrt/src/configuration.rs
lib/core/libimagrt/src/error.rs
lib/core/libimagrt/src/logger.rs
lib/core/libimagrt/src/runtime.rs
lib/domain/libimagdiary/src/config.rs
lib/etc/libimaginteraction/src/readline.rs
lib/etc/libimagutil/src/testing.rs

Before the configuration object (the raw TOML object) was provided via a
wrapper object `Configuration`. This was ugly and not very nice to use.
Now, we only have the `toml::Value` object we lend out from
`Runtime::config()`.
The changes included libimagrt internal rewrites, which are not visible
to the user. Anyways, this change changes the API for config-fetching
from the runtime, so fixes for all other crates may follow.
The changes also removed the support for reading the "editor" setting
from the configuration file, which was not used anyways (in the example
imagrc.toml file).
The CLI-reading and ENV-reading are still supported, though.
---
Closes #1153

Rewrite configuration providing in runtime

---

.travis.yml

The 'bitflags' dependency requires rustc 1.20 as minimum version, hence
remove 1.19.
Also add the newer rustc versions in the CI chain.

Update travis rustc version

---

lib/core/libimagstore/src/configuration.rs
lib/core/libimagstore/src/store.rs

Some refactorings and simplifications in the imag store.
Rel: #1173

libimagstore: use toml::Value::as_str() (for example)

---

bin/core/imag-diagnostics/src/main.rs
lib/core/libimagstore/src/iter.rs

Implements more powerful iterators in `libimagstore` which extend the base `StoreIdIterator` with (for example) getter iterators.
Now these iterators are implemented on all `Iterator<Item = StoreId>` as well as on all `Iterator<Item = Result<StoreId, E>>` (`E` generic).
Thanks to [Shepmaster on stackoverflow](https://stackoverflow.com/questions/47487756/extending-all-iteratorsitem-resulttype-e-to-transform-type) for helping me with this.
---
**On hold** until 0.5.0 is released.
Lets see what the CI tells us about this PR.

libimagstore: More powerful iterator extensions

---

lib/core/libimagerror/src/trace.rs

Closes #1139 
by not calling `description()` when displaying the error.

Improve error output

---

default.nix

The imag codebase was copied to the nix store when using the `default.nix` file... which is a thing we don't have to do to build imag.
This fixes this.

Do not copy imag sources to nix store

---

doc/src/09020-changelog.md
lib/core/libimagstore/src/store.rs

The function was named falsely and nobody noticed. So nobody uses this
function yet - hopefully - as this change is a breaking API change.
---
Relates to #1205

Rename `Store::retrieve_copy` to `Store::get_copy`

---

bin/core/imag/src/main.rs

for printing runtime-generated help output. This way we get the clap generated help output plus our own output.

imag: Use App::after_help() 

---

bin/domain/imag-habit/src/main.rs
lib/domain/libimaghabit/Cargo.toml
lib/domain/libimaghabit/src/habit.rs
lib/domain/libimaghabit/src/instance.rs
lib/domain/libimaghabit/src/util.rs
lib/etc/libimagutil/Cargo.toml
lib/etc/libimagutil/src/date.rs
lib/etc/libimagutil/src/lib.rs

By moving this utility to `libimagutil` we now have a standard way of transforming these things (mainly a standard format for imag).
Question: Should we add timezone information in the format? I suppose not, because this is a single-user thing and the user should not care about timezones, should she?

Date string conversion util to libimagutil

---

bin/domain/imag-timetrack/Cargo.toml
bin/domain/imag-timetrack/src/list.rs
bin/domain/imag-timetrack/src/main.rs
doc/src/09020-changelog.md

This patch adds kairos support in the "list" subcommand for the "-f" and
"-t" parameters which limit the entries to show.
Something like
imag timetrack list --from yesterday
is now possible.

imag-timetrack: Add kairos support in "list" subcommand

---

.travis.yml

Currently we have build times up to 2 hours. That's because travis does
not execute all builds in parallel, but some in sequence (afaik 4 are
run in parallel).
Because of that, we have build times up to 2 hours.
By removing the builds for 1.21 (which is old, 1.24 came out 3 days ago)
and for beta and nightly, we reduce the number of jobs for each build to
3 and thus the overall build time, hopefully.

Reduce number of build-jobs

---

lib/core/libimagstore/src/store.rs

The output was ugly before, as `\t` and `\n` did not get expanded.

Simplify Store debug impl

---

bin/domain/imag-diary/src/util.rs

We need to evaluate the commandline argument first and if there is none,
we use the default.
This patch fixes that bug.
---
Closes #1300

Fix order of evaluation

---

lib/core/libimagerror/src/trace.rs

Was five here, but should be four.

Fix trace count space width

---

doc/src/09020-changelog.md
lib/core/libimagstore/Cargo.toml
lib/core/libimagstore/src/error.rs
lib/core/libimagstore/src/lib.rs
lib/core/libimagstore/src/util.rs

Rewrite without regex crate.
The regex approach was broken. If the following _content_ was provided
in the entry:
foo
---
bar
The regex approach parsed the header until the "---" in the content.
This is, of course, not the way to do that.
Now, the parsing is implemented by hand. Should be faster as well,
though I don't care about this.
This fixes a severe bug.

Rewrite entry parsing algorithm

---

doc/src/09020-changelog.md
lib/core/libimagstore/src/file_abstraction/mod.rs
lib/core/libimagstore/src/util.rs

Closes #1318 
This bug was introduced after the 0.6.0 release, so there is no need to backport this fix.

libimagstore: fix read into single line bug

---

bin/core/imag/Cargo.toml
bin/core/imag/src/main.rs
lib/core/libimagrt/src/runtime.rs

Adapt libimagrt interface to export the functions we need to do this.
This is not that nice, but the best approach without rewriting large
parts of libimagrt.
---
Closes #1233

Change "imag" impl to not instantiate Runtime object

---

bin/domain/imag-diary/src/list.rs
bin/domain/imag-diary/src/view.rs
bin/domain/imag-log/Cargo.toml
bin/domain/imag-log/src/main.rs
lib/domain/libimagdiary/Cargo.toml
lib/domain/libimagdiary/src/diary.rs
lib/domain/libimagdiary/src/iter.rs
lib/domain/libimagdiary/src/lib.rs

Part of #1320 
Patch itself is ready, but the `DiaryEntryIterator` could use some rework as well, as it is not nicely designed (and its name is wrong now, that it no longer iterates over `FileLockEntry` but `StoreId`).

libimagdiary: Do not rely on Store::retrieve_for_module

---

doc/src/09020-changelog.md
lib/core/libimagstore/src/file_abstraction/mod.rs
lib/core/libimagstore/src/store.rs
lib/core/libimagstore/src/util.rs

Unfortunately, our latest fix to file parsing did not solve all issues.
So we have to fix it _again_.
The problem was the `std::str::Lines` iterator, which apparently fails
this:
assert_eq!(1, "".lines().count());
as an empty line seems not to be a line.
Because of that, when reading a file with an empty line at its bottom
got stripped off that line.
This patch removes the use of the `lines()` iterator and uses
`split("\n")` instead. This only works on Unix operating systems, but as
we only target unix operating systems with imag, this is not considered
an issue right now.
This patch also adds extensive tests on multiple levels in the
`libimagstore` implementation:
* On the parsing level, for the function which implements the parsing
* On the filesystem abstraction levels
* On the `Store` …

This fixes the file parsing (again)

---

lib/domain/libimagcontact/src/store.rs

Because we don't want to know the extension of the filename here.

Fix: use Path::file_stem() instead of Path::file_name()

---

bin/domain/imag-contact/src/util.rs

Prettifies from `imag-contact` list output.
Maybe there are more occasions where we want such things.

imag-contact: Join mails with comma

---

doc/src/09020-changelog.md
imagrc.toml
lib/core/libimagrt/src/runtime.rs

libimagrt can read the editor from the config file as well. (feature)
Contains a fix for the case where `$EDITOR` was more than one word (arguments must be passed correctly).

libimagrt: editor in config

---

lib/domain/libimaghabit/src/habit.rs

Followup for #1357 which actually used `Store::create` in the `retrieve` variant of the interface.
I guess I was not properly awake when merging. Shame on me.

Fix: Use retrieve in retrieve variant

---

lib/core/libimagstore/src/store.rs

Simplifies changes from #1365 because `util` does not have to be public in `libimagstore`.
Blocks #1365

Add Entry::replace_from_buffer()

---

.travis.yml

I'm not entirely sure, but I _think_ that actually doing `cargo test --all --all-features` is enough... we don't need to do `cargo build` as well.
Still waiting on more insight from [here](https://users.rust-lang.org/t/is-it-safe-to-do-only-cargo-test-in-my-travis-jobs/16369/3)

Remove "build" job to speed up travis builds

---

bin/domain/imag-contact/src/util.rs

The formatted output should use ", " as seperator for lists of values
---
Changelog pushed to `minor` branch.

imag-contact: Fix formatted output, use seperator for lists

---

lib/entry/libimagentryref/src/refstore.rs

The ref library passed the wrong variable as path which caused the
setting in the entries to be wrong.
This patch fixes this.
Closes #1389

Fix: Pass the right path variable here

---

lib/entry/libimagentrylink/src/internal.rs

This fixes a crash with the (beta) compiler rustc 1.26.
---
As reported via https://github.com/rust-lang/rust/issues/49934

Remove attribute (fix for beta compiler)

---

.travis.yml
scripts/branch-contains-no-tmp-commits
scripts/mkdocset

Change the travis setup to use the build matrix.
This includes a new job which does the scripted tests (are the license headers in place, are there dead symlinks).
This branch also contains a new script for creating (dash/zeal) docsets from the source.

Travis matrix

---

lib/core/libimagrt/src/logger.rs
lib/core/libimagrt/src/runtime.rs

Do not immediately set log level to Level::Info if argument is present,
but check value, too.

Fix log level setting in runtime

---

lib/core/libimagrt/src/runtime.rs

This reverts commit ce0bd9298addfbb9f167ddd06bd2c781eb3de8c0.
Pipe magic is removed with this patch.
We remove pipe magic because its implementation in libimagstore is too
complicated and the benefits are too small.
Having this functionality would be really nice, but the cost-benefit
ratio would still be too high.
The implementation in the store would require a rewrite of the internal
caching functionality in the store, plus some functionality to serialize
and deserialize the cache. This is theoretically possible, but as the
store only knows about "StoreEntry" objects, and only the backend knows
of "Entry" (which would be simply de/serializeable), the complexity
increases a _lot_.
Hence, we drop this feature-idea here.
Maybe, at some later point, this functionality will be in imag. The …

Revert "Implement pipe magic in libimagrt"

---

lib/core/libimagrt/src/runtime.rs

Because we do not implement the store piping and pipe magic, the stdin
stream should always be available.

Make stdin always available

---

.travis.yml
bin/core/imag/Cargo.toml
bin/core/imag/build.rs
bin/domain/imag-wiki/Cargo.toml
lib/core/libimagrt/src/version.rs
scripts/release.sh
scripts/version-updated

We should not depend on the version crate, as it is GPL licensed.
We removed the usage of this crate before, but it was still in the
Cargo.toml files (despite being used in the source).

Do not depend on "version" crate

---

lib/domain/libimagdiary/src/diary.rs

We need to reverse the iterator for getting the _youngest_ entry here.
Also seems to fix the issue that imag-diary edit -d <date> did not work
properly.
---
Closes #1427

Fix: get_youngest_entry_id()

---

bin/core/imag-view/src/main.rs

We must use `ArgMatches::occurrences_of` here to check whether the
argument was actually passed.
If it was not passed, we do not wrap at all.
---
Closes #1429

Fix: Do not automatically wrap text

---

bin/core/imag/src/main.rs

This caused us to print funny output. But we want to catch the output
and print a nice list ourselves here.
---
Closes #1432

Fix: Do not inherit stdout here

---

bin/core/imag-view/src/main.rs
bin/domain/imag-diary/Cargo.toml
bin/domain/imag-diary/src/main.rs
bin/domain/imag-diary/src/view.rs
lib/domain/libimagdiary/src/error.rs
lib/domain/libimagdiary/src/viewer.rs
lib/entry/libimagentryview/src/builtin/editor.rs
lib/entry/libimagentryview/src/builtin/plain.rs
lib/entry/libimagentryview/src/builtin/stdout.rs
lib/entry/libimagentryview/src/error.rs
lib/entry/libimagentryview/src/viewer.rs

In the previous versions, the sink (where the entries should be written
to) was not passed.
This did conflict with the libimagrt holding the stdout/stderr handles,
because it automatically writes to stdout (which we don't want to do in
some cases).
Passing the sink is way nicer. This patch changes libimagentryview so
that the sink is passed to the viewer.
---
Closes #1390

Rewrite libimagentryview interface

---

bin/domain/imag-contact/Cargo.toml
bin/domain/imag-contact/src/create.rs
bin/domain/imag-contact/src/main.rs
bin/domain/imag-contact/src/util.rs
lib/domain/libimagcontact/Cargo.toml
lib/domain/libimagcontact/src/contact.rs
lib/domain/libimagcontact/src/deser.rs
lib/domain/libimagcontact/src/error.rs
lib/domain/libimagcontact/src/iter.rs
lib/domain/libimagcontact/src/lib.rs
lib/domain/libimagcontact/src/store.rs
lib/domain/libimagcontact/src/util.rs

This rewrites `libimagcontact` to be not based on `libimagentryref`.
And it rewrites `imag-contact` to work with the new interface.
---
Closes #1448

libimagcontact: not based on libimagentryref

---

bin/domain/imag-contact/src/create.rs

In case of auto-generating the file name, we should add an extension.
If we do not auto-generate the file name, we should warn that the
extension for the file is missing.
---
Closes #1456 
Not sure whether we should backport this.

Set extension or warn if none there

---

bin/core/imag-store/src/verify.rs
lib/core/libimagstore/src/store.rs

This patch removes the Store::walk() interface.
It was cumbersome and unused anyways.
---
Closes #1470

Remove Store::walk()

---

lib/core/libimagrt/src/configuration.rs

As of rustc 1.26, the `flatten()` method on iterators is preserved by
the rust standard library.
This could cause this code to hard-error some time in the future with
the `flatten()` function actually implemented by the standard library.
Hence we move to use the `Itertools::flatten()` function here
explicitely.
---
See https://github.com/rust-lang/rust/issues/48919
See https://github.com/rust-lang/rust/issues/48213

Fix: Explicitely use Itertools::flatten()

---

lib/core/libimagstore/src/file_abstraction/fs.rs
lib/core/libimagstore/src/file_abstraction/inmemory.rs
lib/core/libimagstore/src/file_abstraction/iter.rs
lib/core/libimagstore/src/file_abstraction/mod.rs
lib/core/libimagstore/src/iter.rs
lib/core/libimagstore/src/store.rs
lib/core/libimagstore/src/storeid.rs
lib/domain/libimaghabit/src/store.rs
lib/domain/libimagtimetrack/src/iter/get.rs
lib/domain/libimagwiki/src/wiki.rs

The previous iterator was implemented to simply fetch _all_ pathes from
the filesystem, no matter what.
With this implementation, this changes. The iterator now has
functionality to optimize the iteration, if only a subdirectory of the
store is required, for example `$STORE/foo`.
This is done via functionality where the underlying iterator gets
altered.
First of all, the interface was changed to return a `Entries` object,
which itself only covers the libimagstore-internal `PathIterator` type.
This type was changed so that the backend implementation provides an
"PathIterBuilder`, which builds the actual iterator object for the
`PathIterator` type.
The intermediate `StoreIdConstructingIterator` was merged into
`PathIterator` for simplicity.
The `Entries` type got functionality similar to …

Optimize the Store::entries() interface
